apiVersion: ENC[AES256_GCM,data:+o8=,iv:1IgKcQk6xxxqk0nLoDYs4CZpdXFIuEBF1tXIjb5M6Q0=,tag:dK7la9qGEfuvRgrvM6hu5g==,type:str]
kind: ENC[AES256_GCM,data:BcxUE+bU,iv:qahI72GryN2iPT7ojz5dkGJh9Cad+4myYn2V4DrrLio=,tag:+V0LD9ySi5Pp+ISHiIs6WA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:nsJJ1nH/j3zKRPCy62F1,iv:BKq5jSMmIkPMHcz0sNgZASLnJN5zEwG0Q6TUolDiWUo=,tag:P2QtYxDnYb23F9RAQzhazQ==,type:str]
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: ENC[AES256_GCM,data:WnUXsQ==,iv:C+BGawIIN8c9day1w2FJP6jx4YfMo2vYcVU7V24JncQ=,tag:2JwZuaRShGrKJ58waVPYBg==,type:str]
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: ENC[AES256_GCM,data:fJFOUQ==,iv:dQMPqi6dF54QwOrvdcmdBt5/Nhlq/sZI4sVq3uCDuxY=,tag:bzJIHNJMdKiuiObdsBKWgA==,type:str]
stringData:
    aws_access_key_id: ENC[AES256_GCM,data:NnVFjs3+qTjo49k9VLW/qEYAlO0=,iv:RmaxjoB+J/GFqHX1B5MxjvrR3nliEtmN5nM53Rsaii8=,tag:J8npajh9S67icXFxFTXJLQ==,type:str]
    aws_secret_access_key: ENC[AES256_GCM,data:jgQsG5QXwDNy63NFDcHCBKAnyI0UQ/GeAhZAIvbtjtKM16dtgbX2yQ==,iv:kNMR7HDgQdYMEUh2yToQuyIBnZP+MKGPjzDAmHmru/0=,tag:hkJYzHWrXjV24XEM81zsrg==,type:str]
    aws_homelab_remote_state_backup: ENC[AES256_GCM,data:1p/wT5lgx7iDdnguhJMq+qlk73kLByLuBT7z9I4ORkI=,iv:M4OvjnHdPtnVnR8fq01psr471gYu6dlvofgurWZRVSs=,tag:WMX4UYY3m2P7qr74gbZAJA==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:626956831217:key/f22ea8b8-ec28-4d80-988e-7372419dbc28
          created_at: "2026-05-31T20:12:15Z"
          enc: AQICAHgf2Bz/yC/N+d80dqtXyzpCypiaZx1Lgwl8YcJR1TYnOAHzbmUX6m0u25BR0TPxlswNAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMlLqIb3PqiOIigsm5AgEQgDtyxDz9tZgZmOouRI6FXcH3d+WSyjZnGvETiAM1hPhzTKMMufiIPsngUd5SKup89e+Z2oeWqYtrE4oRsQ==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-05-31T20:12:16Z"
    mac: ENC[AES256_GCM,data:WIwLRKAhPOAQKeXikJzcjD4J3aT5ALGg3Usq9nqVpkyH7VxDeqZ4JaxR0dxS5pfwRkFIsjKohjKk+x3gWoSVlTT9wDmDySPf1bo3ZtneW3IQhhg+cBOx5MApnsfUN7fREHdKk93G5jTa11KWzOXQ2hQl25NcyxJH7wa6Xn4qauY=,iv:X3WeY8tmt/U4IeZBLlvLcmoC81YirJQznb9B0vKehD0=,tag:MnCMYmNrroAqUzQWk7nHBQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|apiVersion|metadata|kind|type)$
    version: 3.8.1
