apiVersion: ENC[AES256_GCM,data:bT8=,iv:vyHhmvt52A8fk/ZFyEhEfKQnZLTqlfeDIm/JLp61Gj8=,tag:AV79g9o2MijRxIiRj6xBsg==,type:str]
kind: ENC[AES256_GCM,data:tGeO/QjG,iv:4SeXKkqo22KuWMzS6yteJxb8etU4Y1JNDG6ilSPaQUI=,tag:CtDmfhV/yBeX9Udc4bzn6w==,type:str]
metadata:
    name: ENC[AES256_GCM,data:RkKRtvGLHlVQEdMr+WBR,iv:m/OmBtBVoOOJdjoTBm0Wh/Oc+L5OLAw0dkKy3Mz4uT0=,tag:5LfEJ6Oupxt4CUyK/J45cQ==,type:str]
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: ENC[AES256_GCM,data:/SXI6Q==,iv:mjb9eNQBB6/IUnqW5KK3IGFKwE7tTYsPLwJFYyHc8tw=,tag:VllsAo11bkCQ3vaxyurKLw==,type:str]
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: ENC[AES256_GCM,data:/VL+2g==,iv:aIpt0VYhxYIuICSTzdQAZP7t8G2wX3lHAv5D1wy75pM=,tag:5ypCyq4GxCOBICNSIo+R7w==,type:str]
stringData:
    aws_access_key_id: ENC[AES256_GCM,data:lq8N6/soUWD1RqILklN32ThVwgA=,iv:IkT8p4AsTfnRHdCTiwurgEEZb46i8jdE+J0khn/6dfM=,tag:BSE05rXniv8uk9P0lhdhWw==,type:str]
    aws_secret_access_key: ENC[AES256_GCM,data:gVLG3IZ4s9OuRdrYmVDqGuw8JF0plBdQOP08epseiBpJko+eomC9lw==,iv:Ua01Wvq+9JKIcErmwsbWuxtCXWhyKq/fkERrJIHIbAg=,tag:e/IvNmmmL/BDE/u5ZG0dCw==,type:str]
    aws_homelab_remote_state_backup: ENC[AES256_GCM,data:nbhaQURU4tEPNu93lIUJU9wK+jkvwnJxwv7iCodwQRA=,iv:CUtJUgXWqdiYyyFesmUuxDYa1BYuynqxEk4ky6j4QPY=,tag:QB+YeV0o3c7tR3eA17AT7g==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:626956831217:key/f22ea8b8-ec28-4d80-988e-7372419dbc28
          created_at: "2026-06-17T19:38:51Z"
          enc: AQICAHgf2Bz/yC/N+d80dqtXyzpCypiaZx1Lgwl8YcJR1TYnOAFmrNtG90BojB8vLFJP8p8IAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM8rL14nBPHA4PxOoUAgEQgDvxnteS2ToU0n9OgO6fhPILbJqYlIqtLRLNRFBjcAzNC1Y1RdK+jpyDt2YhCeI8R1tk1OcivO55UzBw6g==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-06-17T19:38:51Z"
    mac: ENC[AES256_GCM,data:HEPdfxeqlfzYO8Uoxr9H0PKlkhlPB5ODUnUc0li0FjL+eQU0Sb1WMmqd90Xj3ERTjCJGfm8e+Vq6Fy+WISG4EoRwfHbmWa8MDw0ysL5Fw/CsBVhfQ/HYMIJDk4Vv09BoH1y4edub6gAsIUgDofdWFWhSDmjmRG49rKfvQKfjIdg=,iv:yc5M+68y9FpQYaSY1+MNAoq/94QttQ1SS9rjTNufhA4=,tag:+e7gLUPnL4uIjvzeCZ61Qw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|apiVersion|metadata|kind|type)$
    version: 3.8.1
