apiVersion: ENC[AES256_GCM,data:Yfo=,iv:fLWDIq8ZtBZRpcRf5F3gLGT4udzBo6CziMMm8JwAgdw=,tag:ylkvmGCR8VCg64FIsP5quA==,type:str]
kind: ENC[AES256_GCM,data:dM27lbFL,iv:hk4BgGmezVgxYg7x5Vsbht4ikExwiQQc+B3Fwl14PTA=,tag:WyKunRLA8vboysucr4lTyg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:DEzIvo58XBubZq/2aPh/,iv:Nn0cw+XiehqY/oJfvLVVYgacDGztDfa9zxyN26H2Jzo=,tag:f33qj6Hps1gs4HvT1ocKJA==,type:str]
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: ENC[AES256_GCM,data:AsklrQ==,iv:Mh/y/HlrMneK/tpa1AGVCL0EALmnYh4cgvmqdKWoWb8=,tag:f61IipBUsu00VQPMIAW5Lw==,type:str]
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: ENC[AES256_GCM,data:kYrXpw==,iv:4bkGaNgttSCdmnGkFk3ah2MmIfdo1BDOk1Xzg0YAoYw=,tag:FXOmKC0TDelJ6V7/o+LTRg==,type:str]
stringData:
    aws_access_key_id: ENC[AES256_GCM,data:TFsfnZWuaGlRozKFaCuOfKTkFis=,iv:eOEyvWzSmRQdtkoyEhesNRf87X4kcN1Kidux2197PHg=,tag:AT684VIa5DkYRURvgavW3w==,type:str]
    aws_secret_access_key: ENC[AES256_GCM,data:Ovri56h7Ma7ZfJcackoRH1LNlHOjf64UNWRW+ee2MmG8nocc1qY3kQ==,iv:JArNEhVf+x1QxgnO9ufIoBn3IKktvqVpB58WThYGN4E=,tag:gNxnsNMJtaqclc2FGpGHuA==,type:str]
    aws_homelab_remote_state_backup: ENC[AES256_GCM,data:iD3aEzDbpN98CVAZeTgkTUJOktbUPI1W4wpZ9osI7Fg=,iv:ojtI7zOhBRrugqLd3qmx+sceYICw1n2ErnZHFGruSiw=,tag:sXwWrMtLDtHeWF4ExQBvig==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:626956831217:key/f22ea8b8-ec28-4d80-988e-7372419dbc28
          created_at: "2026-05-23T19:00:03Z"
          enc: AQICAHgf2Bz/yC/N+d80dqtXyzpCypiaZx1Lgwl8YcJR1TYnOAEfFRpQzqG9rMBS7aorZTJuAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMoO5ScJqUYWTqjK6VAgEQgDvYSKoGUVkdtkjb9X7sT27i8Ban9jcM7Ju0ot0Fj1/Y/rUQTboEL7hPzRT88W61YG1nypZ4COvn7MvtXQ==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-05-23T19:00:03Z"
    mac: ENC[AES256_GCM,data:06TIiT/5bHG4IGdeE1O/YMLIKAwdN6t2l7RmdxDsdjxA41/s4Sehd2K8mnOhWRnDpakOcsGSHy0iXCoo/wKevnwkarKCmKZ2jMEWFCgIQFjsusDyIkUwn0l3K1iQgc4+qYy3nvJClF2dpdTsMks4KB/McwLuQNkx0kHt85Y+q4o=,iv:n2wePh0KoDac5qKJKgaAwLMtJf2LZKZVjARMCYgC0vU=,tag:/CiJuIckanziDDdYPTIGBw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|apiVersion|metadata|kind|type)$
    version: 3.8.1
