apiVersion: ENC[AES256_GCM,data:rYk=,iv:eeFB6heTOfQ8TG2oycAhTtce002ib7ZY0vNxA92IoSs=,tag:73+ZLNYO+IeuiRfPS0AhGg==,type:str]
kind: ENC[AES256_GCM,data:8b73bF09,iv:bTRw9luu6McTnZ+o/AtT55CkZl4paj+fW2/sCZiwwcg=,tag:OjVnQs+hmfPzbXYfCegSRw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:wbYoPXRbXPRwriUHnZfmYA==,iv:JoOdN8jKNwrdDjsSlnS6YwI4e0+w7FCBxnS/JenQrVc=,tag:uj0rdIwCTp/mSwt31tSE+Q==,type:str]
type: ENC[AES256_GCM,data:pmz6XSKl,iv:uErAxEGt570qgA3RNJH4TiR+tYln4438nT0CYysfSVs=,tag:darTRbn4yuMcVuBnAEd1VQ==,type:str]
stringData:
    username: ENC[AES256_GCM,data:PiYI9rtn8B4AzJs=,iv:nKNBB5mXNyxCDcSI0++JR1Wz02erDEKatCFzgPfmmlo=,tag:J0XfBBvSTAGTcbnNGUc8+Q==,type:str]
    password: ENC[AES256_GCM,data:oFyQr2KIX2BMlzJqLPCShbhp8vvPr76X5OsGfuIt4+dB5mv4BCAQNQ==,iv:g1qsFd3T2WyYj77xHE/5qNPYZT57iWD1TRLwHT9SZKg=,tag:5LXK3V1rzNLzL71ubi0huA==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:626956831217:key/f22ea8b8-ec28-4d80-988e-7372419dbc28
          created_at: "2026-06-17T21:36:39Z"
          enc: AQICAHgf2Bz/yC/N+d80dqtXyzpCypiaZx1Lgwl8YcJR1TYnOAFIAaIxvneqKyPUjV6BalPbAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM4MFwV2Ji0gZIOZbUAgEQgDv5vcBhqGoIXTQtml67Pt9Fbuu+zYSl2DRrVcjZPL1ERALBsNk7qkx/9gGS7ejTIWrS/jg8MM+hZUypEw==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-06-17T21:36:39Z"
    mac: ENC[AES256_GCM,data:xQtBOMKCpnQKxLepSqwGrg+qbrU+1yXxq6/+Agfa7HzsTBK9wuskfffyb1EATSC/iKUWhAiHtMeew3doUwBcdR+uIBy6Yr8VPW3+YFcdZRvLPzospAGjrH4gLLGjgPo9gyWNn+4j9FKXFn28cOMHCpsf/CmPaE70QDXCshXSV2M=,iv:nLT9iXa2Q2hqqticI0DS9Cxm/NwdALJnvsP16kuK16U=,tag:rCd107Ii2MZABeg7UMU9sA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|apiVersion|metadata|kind|type)$
    version: 3.8.1
