apiVersion: ENC[AES256_GCM,data:p7Y=,iv:q74+iiRPvlIKFJsxCM88VlIlzj7OzPdMChrRfygffLg=,tag:r8yfg1HoeyAeWun7m6Y9Fw==,type:str]
kind: ENC[AES256_GCM,data:z2vz+xqp,iv:LYgBPF/OdeQWLTjELlHtR4mXZFoZw5VHXokdNi6jN9Q=,tag:w1MDADMwMavpUhKGQ605pA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:TWH1w60u79OIKRc=,iv:vlxagXv5ECsjh7VtQJEhVqfZqSeRwFi23ErHWYNFvus=,tag:/b4+is72xgnQHjOcjZZtYA==,type:str]
    namespace: ENC[AES256_GCM,data:kv7lSs3V3biapA==,iv:V/bvdSaTN9Lxdp6umAZSPbaGLFx1Im9bB6/soz2Q1EY=,tag:qlvXHtg8YcAOSl7RfFbHMA==,type:str]
type: ENC[AES256_GCM,data:Fw7Jg+hb,iv:aN6rmEnkZAmQKK6Ap2AF/Qu/s8rkdzadTRG8vGRa/FY=,tag:vGV+y0d2BEcYnSHxMVN94A==,type:str]
data:
    N8N_ENCRYPTION_KEY: ENC[AES256_GCM,data:BZL2/2dZXEKkIcvKeXpe5acfsim6RACLjPyhV0QZ6frPtJ3oTcIzZCSK9lg=,iv:vS0m3DUV0aS9PoWuGdKgE1GuONNLAk5lKO3gJiJQ/CQ=,tag:JjVSd253/TtEghQmB9AxWA==,type:str]
    N8N_USER_MANAGEMENT_JWT_SECRET: ENC[AES256_GCM,data:0V4Y3nbBr8C4N8JvvTlv2GtGvquhvIwR,iv:dyemM6Io+E4FYNkNfFY+Hol11lDnC7kT7wifSVN2JGQ=,tag:FEK+OgdDplFOafJnI9IN/Q==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:dfbfUhTYDIolr2Priy0ZJYMwuUDuuUVR,iv:NR1fWcXksD7wDqp1u3xOkXK+rsUpkXpeFox13YTXT/A=,tag:zHlmBqQ14RDLpm2YwGJawQ==,type:str]
    CLOUDFLARE_API_TOKEN: ENC[AES256_GCM,data:gPNoflup6rn7Au7Ib+0fi6Bk5M8qg+pJFODgQsz5Oc2x40NBGHA6RAzI5h12CGIQ8MX9zgFNqSc=,iv:LpDo9l7gznZV5ZksX0OLDR6eHR6vt4gMK9Hj9ves/hg=,tag:HCyLd0gqwE2+yMBLSsXCRw==,type:str]
    WORKFLOWS_BUCKET_NAME: ENC[AES256_GCM,data:5IIfWMnRcUr5tuL+Y1fnEagQRsSmgQXdH6og9i+gBFn3ntFkYTTMKnC03+E=,iv:Xq/UD+nux3iO8P3GYhokH465G5DZAVpgg1v8xlNUEdQ=,tag:5L1FrHJ+s4q2EcUPNVmiBg==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:626956831217:key/f22ea8b8-ec28-4d80-988e-7372419dbc28
          created_at: "2026-05-29T17:59:43Z"
          enc: AQICAHgf2Bz/yC/N+d80dqtXyzpCypiaZx1Lgwl8YcJR1TYnOAGCLmWUQmFSFAVEEqVmqZghAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMxOgTx4Nih8o49+4/AgEQgDvsnKM96Cvm/yNNfeX2DabGabXmA2xx4L7uyeYNfgfZvGlKYeJgVF1B6Q6304QNsYDhaXtAfZNnjnkTFg==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-05-29T17:59:43Z"
    mac: ENC[AES256_GCM,data:xCAHPFj/ceZL7SsRPSEkPoelqRdilyLKLWQ8tx2KtXhfRQpaYtEWK8SMv4zzGT+4uZ/fQbYBsYsA7LAzWEfrkIYWonUhMM5DKJ066GEyHKBNoG5cnlkwVonp6v4qHJgqef+L5Ky8l2gan4ePI6GaoFIb1WGOraone6RsXCu9Rjk=,iv:uiDEHmyaQ2Zn49HQzm68NlOfzH0GUckyRbdYT3c1GWU=,tag:xDyipwWT1Pq9wKTFuljCQg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|apiVersion|metadata|kind|type)$
    version: 3.8.1
