apiVersion: ENC[AES256_GCM,data:7JQ=,iv:MX7FkyezDNblr3+6OI107wQr/sBwsoIo3Kfc7urdI+A=,tag:FGcxZqW0aAdpvloXLLXYPA==,type:str]
kind: ENC[AES256_GCM,data:uFdQ994o,iv:ZS6nAMkiwk2iFycVyqL4jOWggqJkRyROtEbqFBdrG9k=,tag:bKbPDeffiMEIEQTtfgw4Tg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:S/pPt5yQmumpQyI=,iv:zzR4IBFq/qZJ4Pg8DOnNlvD4+aAL9frQP+a4Vo6VXoY=,tag:u1RSmoaXP3tVECOSjzlq6g==,type:str]
    namespace: ENC[AES256_GCM,data:ENIb30pXTKyDmA==,iv:w9ay43tI1p7ou2+YKQSK5D4TiroWSKj1ij7a74UMfGI=,tag:5CIaKaUlSbNH/D88x3lROQ==,type:str]
type: ENC[AES256_GCM,data:pgzu16O4,iv:QYp/bGfxSyDRx4mxOxWzNGohzjPNFFDGZ9JcIiRH9Pk=,tag:d7LC+0KPdPm/44Q4svqZEA==,type:str]
data:
    N8N_ENCRYPTION_KEY: ENC[AES256_GCM,data:XBm8C45C7LuIBU3+F3xMdDyclfxpci40XVkY7dHKCLQoYtVF4uKq+h7oHnk=,iv:itsRFd2GOarGIteu1abdGpqUikml7SOMR7DI8FeWrMU=,tag:aRfJPjLzQ1OYlNb7F9wY1Q==,type:str]
    N8N_USER_MANAGEMENT_JWT_SECRET: ENC[AES256_GCM,data:LnRkMzOI0ilWOu+ICeeKAxowWFRbDxE0,iv:HIfOAce9f1oafcZi6H3dh2dmnk8kKHVH8y3O3Dkfv2k=,tag:DSmMGATpIzLw2ZrNsQO9Fw==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:tJM3WrBJ2iCo4E5Y7ulgl3GSu2n3rjn0,iv:5nY4BUsh9UNMJBOdXnr5ol2zvPra2/oRoSwoxKIiFIc=,tag:J8kpoNRukTj22063YFJ/1w==,type:str]
    CLOUDFLARE_API_TOKEN: ENC[AES256_GCM,data:c6fupgn7zrSg0AxYl5uGLkyNAO4VK0ynaIG915kv79jhSMo9DKsGchT3FrEslY5p6GSwI0aBIkI=,iv:ru0vwaFPb3z0USqZHS/9r44IVfRtunBcJmkcbWVjpbQ=,tag:cdYAtiOHzHGKsrtH0hW3/A==,type:str]
    WORKFLOWS_BUCKET_NAME: ENC[AES256_GCM,data:Yci0NHQWenv8EmSOiDuKyQ6jZqOhUTcc7HFYiun9cCCL7lXDvLaXQlmDMI4=,iv:c3KmGWRPHGUPk+G2+kJYF8sVSax25AYOxfIJ9fhpHi4=,tag:tq96Na+SmFwQhFEzJv08aQ==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:626956831217:key/f22ea8b8-ec28-4d80-988e-7372419dbc28
          created_at: "2026-05-23T19:03:36Z"
          enc: AQICAHgf2Bz/yC/N+d80dqtXyzpCypiaZx1Lgwl8YcJR1TYnOAHIjdX8OLVIQaespNJK/7WzAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMBV1mTD2lJHIWuLQ0AgEQgDuw0sOuOhiZKRTdNH7MfDXbMLWKmMzs1CIrEp4gboqRNIbT582HrRWMSggue1Csu/LbX08Q5iImx7O5oA==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-05-23T19:03:36Z"
    mac: ENC[AES256_GCM,data:sG62jyEHUWUd2xh6XsTT+szbEF38pIh702PbMWMvXW+AvPL/jemhcnw3CPWR3ZGBM7wpyIIKWnML7D7ICA6bwq8lX5np0w4hfr0jNA5sKFoIPKA5ubJPBR3GrqS1RBMfBCicSqyHRqOBZnUXwEU96eT28f/whW3KSqwEHvE/m5Y=,iv:W/F0h/s07BWOEXJLH4FeQep1+71viKAVGjMeeT7Tgy8=,tag:GJdhlguV0MBVSmQdu5tvjQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|apiVersion|metadata|kind|type)$
    version: 3.8.1
