customization:
  systemExtensions:
    officialExtensions:
      - siderolabs/i915
      - siderolabs/intel-ice-firmware
      - siderolabs/intel-ucode
      - siderolabs/mei
      - siderolabs/thunderbolt
      - siderolabs/util-linux-tools
