---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama
  namespace: ai
spec:
  selector:
    matchLabels:
      name: ollama
  template:
    metadata:
      labels:
        name: ollama
    spec:
      runtimeClassName: nvidia
      nodeSelector:
        kubernetes.io/hostname: mlops-work-00
      containers:
      - name: ollama
        image: ollama/ollama:latest
        ports:
        - name: http
          containerPort: 11434
          protocol: TCP
        resources:
          requests:
            cpu: 200m
            memory: 1Gi
            nvidia.com/gpu: 1
          limits:
            memory: 8Gi
            nvidia.com/gpu: 1
        # securityContext:
        #   runAsUser: 1000
        #   runAsNonRoot: true
        #   privileged: false
        #   allowPrivilegeEscalation: false
        #   capabilities:
        #     drop: ["ALL"]
        #   seccompProfile:
        #     type: RuntimeDefault