apiVersion: ENC[AES256_GCM,data:NH8=,iv:hox4V6UG+cNjMHdyPEd35wyPcx6OTAZxvvfCzz1sfV4=,tag:Szi5fR3jpfQHuDMIm6vjwg==,type:str]
kind: ENC[AES256_GCM,data:xcfo/LYX,iv:NeZM1GBiz/AP3LRGU8T7+toCS8Ni04ENRN6+Y4Raw88=,tag:VfBjIplG1jLJ6RMXhsKPtQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:sTbAylUruk5bh26gPYwrNghqbMVEyXtMvri6u8U=,iv:YfHk5Ydr/7X2cd/PWzM4DVXkY9WKPpNXYYTfRPZRT20=,tag:Jghl9qf2DyflNtA3eovi9A==,type:str]
    namespace: ENC[AES256_GCM,data:qrBToeKXpQ68xA==,iv:ea4QrL/IabA7O4/YmkeliikLYvnekT0K/eSfFRwrDUw=,tag:9F4bwi9JAf0dwAkONSQcKw==,type:str]
type: ENC[AES256_GCM,data:4kvCA5UCP1sjdJccq9MLjjcP0glqe/O8,iv:q8NwRszMaCDlamJIImnBiePdkc01lOux1rOlUXmBLBg=,tag:dXKt6oc1CZHeXmrmhBh8sA==,type:str]
stringData:
    username: ENC[AES256_GCM,data:UdnLNOmIEYE=,iv:tl/TFUpstQFNNCtg+DPwaNmR9GqnMigWD2YjnwmZeeM=,tag:+iMOjRaf8LIkjiE3YStcJg==,type:str]
    password: ENC[AES256_GCM,data:PrH+8A06l1s=,iv:zenNeN5KANAebxQbZG56DKMQWeAo4/j6o812arFTSso=,tag:U5AShl7REVM1ML/ypkkTGA==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:626956831217:key/f22ea8b8-ec28-4d80-988e-7372419dbc28
          created_at: "2026-05-20T01:20:50Z"
          enc: AQICAHgf2Bz/yC/N+d80dqtXyzpCypiaZx1Lgwl8YcJR1TYnOAEEhqsEHTbcx2Td7wu2i/ULAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMwKDmcw2+e8ThFn0jAgEQgDuG/D5NuViJ/oye9gyk8XqHnCmhOcXblR2ewozHwGry7t70Pd+sFFT6ShkvF+9zChqzF98VLerxyrNPAg==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-05-20T01:20:50Z"
    mac: ENC[AES256_GCM,data:jFkHbxNuSYtZXpHknM6Cm66GSnbU2BJDmbjey+/YaFia4YyCGKq7SrhCqi8Ko1I9+xfNbnk+urp5pbXXjAyyqyKY9VR67HJa8JXIsrWjLIXKxssRoN9qeLoQVv74azJox+F/AfnSxzsBBOzH9t7FX85X1ACzA3mqCVUQqiSKshY=,iv:S9xapbzyYglLez8PtLSfMq50p8I0SgGOTPS0An42BFg=,tag:A3wd4pkHPU0wCutVZeEdLw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|apiVersion|metadata|kind|type)$
    version: 3.8.1
