---
version: 3

vars:
  KUSTOMIZE_FLAGS: --enable-helm --enable-exec --enable-alpha-plugins

tasks:
  deploy:
    vars:
      CLUSTER: '{{.CLUSTER | default "application"}}'
      KUBECONFIG_FILE: '{{.ROOT_DIR}}/kubernetes/generated/{{.CLUSTER}}/kubeconfig'
    cmds:
      - |-
        KUBECONFIG='{{.KUBECONFIG_FILE}}' kustomize build {{.KUSTOMIZE_FLAGS}} ./research/kubernetes | kubectl apply -f -

  destroy:
    vars:
      CLUSTER: '{{.CLUSTER | default "mlops"}}'
      KUBECONFIG_FILE: '{{.ROOT_DIR}}/kubernetes/generated/{{.CLUSTER}}/kubeconfig'
    cmds:
      - |-
        kustomize build {{.KUSTOMIZE_FLAGS}} ./research/kubernetes | KUBECONFIG='{{.KUBECONFIG_FILE}}' kubectl delete -f -
