apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: n8n-storage-shared-pvc
  namespace: automation
spec:
  accessModes:
    - ReadWriteMany
  volumeName: automation-platform-storage
  resources:
    requests:
      storage: 5Gi
