---
apiVersion: aigateway.envoyproxy.io/v1alpha1
kind: BackendSecurityPolicy
metadata:
  name: openai-apikey
  namespace: ai
spec:
  type: APIKey
  apiKey:
    secretRef:
      name: openai-apikey-secret
      namespace: ai
