---
apiVersion: aigateway.envoyproxy.io/v1alpha1
kind: BackendSecurityPolicy
metadata:
  name: openai-backend-security-policy
  namespace: ai
spec:
  type: APIKey
  apiKey:
    secretRef:
      name: openai-api-key-secret
      namespace: ai
