version: v1alpha1
debug: false
persist: true
machine:
  type: controlplane
  token: e6o2hc.zbduvyfo55s5q88w
  ca:
    crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJQekNCOHFBREFnRUNBaEVBOEtHa1pBTkZZUDN1SThtQk5vanE3REFGQmdNclpYQXdFREVPTUF3R0ExVUUKQ2hNRmRHRnNiM013SGhjTk1qUXhNak14TWpBek5URXlXaGNOTXpReE1qSTVNakF6TlRFeVdqQVFNUTR3REFZRApWUVFLRXdWMFlXeHZjekFxTUFVR0F5dGxjQU1oQURHMURod21KRVVscDY1d0JoT0kzZys2dTBxRFZoR1JXMkprCkVTZEZNV2VzbzJFd1h6QU9CZ05WSFE4QkFmOEVCQU1DQW9Rd0hRWURWUjBsQkJZd0ZBWUlLd1lCQlFVSEF3RUcKQ0NzR0FRVUZCd01DTUE4R0ExVWRFd0VCL3dRRk1BTUJBZjh3SFFZRFZSME9CQllFRkJkVlkwdWF3QWZtWlFPNgpieG5tcUpKWFBVdE9NQVVHQXl0bGNBTkJBSnpmdjFxTmhMR1E2cUJIMTJRcHhJQlU3eW1uTWJzcnVMaGhqYk9CCmpMdTh1MW1MRDNDQlRFSEdJbTlSeUZpSS9OYW5vU0NWb2FDK1ZPdk1uT254MHdzPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    key: LS0tLS1CRUdJTiBFRDI1NTE5IFBSSVZBVEUgS0VZLS0tLS0KTUM0Q0FRQXdCUVlESzJWd0JDSUVJS1VJN2RrSVBvSWM3VnI5alFxVHlseXRCN1VGWEdJRUdoeEZwMjUxQkFlWgotLS0tLUVORCBFRDI1NTE5IFBSSVZBVEUgS0VZLS0tLS0K
  certSANs:
    - 192.168.2.20
    - master01.local
    - 127.0.0.1
  kubelet:
    image: ghcr.io/siderolabs/kubelet:v1.32.0
    extraArgs:
      feature-gates: GracefulNodeShutdown=true
      rotate-server-certificates: "false"
    defaultRuntimeSeccompProfileEnabled: true
    disableManifestsDirectory: true
  network:
    hostname: mlops-master01
    interfaces:
      - interface: vmbr0
        dhcp: true
    disableSearchDomain: false
  install:
    disk: /dev/vda
    image: factory.talos.dev/installer/e3fab82b561b5e559cdf1c0b1e5950c0e52700b9208a2cfaa5b18454796f3a7e:v1.9.1
    wipe: false
  features:
    rbac: true
    stableHostname: true
    kubernetesTalosAPIAccess:
      enabled: true
      allowedRoles:
        - os:admin
        - os:reader
      allowedKubernetesNamespaces:
        - kube-system
        - default
    apidCheckExtKeyUsage: true
    diskQuotaSupport: true
    kubePrism:
      enabled: true
      port: 7445
    hostDNS:
      enabled: true
      forwardKubeDNSToHost: true
  nodeLabels:
    node.kubernetes.io/exclude-from-external-load-balancers: ""
cluster:
  id: ylEnoSCo-05IU69t9_c7aHmzz1tDPgPfu1dqwi2Zajs=
  secret: rDwZzDiABaFVZYWdlUSrMe9LmtmzBMLXBXNnaSjPlmE=
  controlPlane:
    endpoint: https://192.168.2.20:6443
  clusterName: homelab-mlops
  network:
    cni:
      name: none
    dnsDomain: cluster.local
    podSubnets:
      - 10.244.0.0/16
    serviceSubnets:
      - 10.96.0.0/12
  token: tfbqhx.s7fq4lg1hlq8doa6
  secretboxEncryptionSecret: JZlWOmaVMdR6lEmo5IuQA3juwmS2HxAzwPZzmet5Ec0=
  ca:
    crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJpekNDQVRDZ0F3SUJBZ0lSQUxLTG5kNkp0dE1JbEEycXAwVUZqeFl3Q2dZSUtvWkl6ajBFQXdJd0ZURVQKTUJFR0ExVUVDaE1LYTNWaVpYSnVaWFJsY3pBZUZ3MHlOREV5TXpFeU1ETTFNVEphRncwek5ERXlNamt5TURNMQpNVEphTUJVeEV6QVJCZ05WQkFvVENtdDFZbVZ5Ym1WMFpYTXdXVEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CCkJ3TkNBQVNubWswWlJkaGxPOXZtdnZZT3AvSFBiVGh2OERjekJDNlZ1eHNWdnVheDgvT09Uc1VkWU5ObFRzYWEKU2k2UncxcVBMcS91SUQwZ2tUQ0ZacVF2RW9XaG8yRXdYekFPQmdOVkhROEJBZjhFQkFNQ0FvUXdIUVlEVlIwbApCQll3RkFZSUt3WUJCUVVIQXdFR0NDc0dBUVVGQndNQ01BOEdBMVVkRXdFQi93UUZNQU1CQWY4d0hRWURWUjBPCkJCWUVGSWZ6cWZPUlJuQWN1a2Y0QlJyMGxsZWNZRTV1TUFvR0NDcUdTTTQ5QkFNQ0Ewa0FNRVlDSVFDK3VmTlcKSmljd1hpaXBPSitXTjVTWjR6OVZQUTk4WEdpaVFOckRVTGxxQUFJaEFPSWtyN1FLWXllQS8rMXBYZ2swdXZEawpOUGZqYU1TUnZBeUh3S3Q0bzNyOAotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    key: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSU9pQWxhbk1KYXlNZU5IdlhpUGZvMjc0azlKR1Jic29QMVhWSGRJalBkNytvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFcDVwTkdVWFlaVHZiNXI3MkRxZnh6MjA0Yi9BM013UXVsYnNiRmI3bXNmUHpqazdGSFdEVApaVTdHbWtvdWtjTmFqeTZ2N2lBOUlKRXdoV2FrTHhLRm9RPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
  aggregatorCA:
    crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJZRENDQVFXZ0F3SUJBZ0lRTTVtN05ZdGRkUDlSdDE4S2ZsNFgrakFLQmdncWhrak9QUVFEQWpBQU1CNFgKRFRJME1USXpNVEl3TXpVeE1sb1hEVE0wTVRJeU9USXdNelV4TWxvd0FEQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxRwpTTTQ5QXdFSEEwSUFCQml3L3BzNFF0aVRseU9idzBtVkJoTE4wSVRWYkFBMkl6TkpTaXJCS1J1YVc4cC93Y3ArClFsV1R2MXRPczhpeGpuREZhZDRjWDRrSXk4YVhwY2c1ZWR1allUQmZNQTRHQTFVZER3RUIvd1FFQXdJQ2hEQWQKQmdOVkhTVUVGakFVQmdnckJnRUZCUWNEQVFZSUt3WUJCUVVIQXdJd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZApCZ05WSFE0RUZnUVVlQ1grcUZSd1BVaElTMjg3MzZIZ1B5L1VpT2N3Q2dZSUtvWkl6ajBFQXdJRFNRQXdSZ0loCkFKSGtEZ2NDTEVrLzJ6N3dwSXFRVUtYdmptVnVhZGRTc0Z6d3lha3lhVFpjQWlFQTVudVdFdzMzSDZEejBlNGkKQ0JpQWlQRFY0ZW5ISnBFYUkzQkI3VUhFTG93PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    key: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSU5TL2xSTmVoYUY4TEFFamkxSWgyeDBNMW5MSEdNbzZaQmZxaDBtak1FMXRvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFR0xEK216aEMySk9YSTV2RFNaVUdFczNRaE5Wc0FEWWpNMGxLS3NFcEc1cGJ5bi9CeW41QwpWWk8vVzA2enlMR09jTVZwM2h4ZmlRakx4cGVseURsNTJ3PT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
  serviceAccount:
    key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlKS0FJQkFBS0NBZ0VBc1Y2VnU2NFNQV0F5eHI5c0IwSmU2YWU5Kzl1M3lKNERhQUJEQjVLalZiMGM1Y3o2Cmxod2pkdDZvZE84WmczdkNTREVzd3hXUGVCcFY1cjlKakpXSUNZS2ZWZlg1d2FuRFRtQzBueGE1bms5bDJzRzYKZjdJYVFRWjBrZk4wSWdPNVdpdzlWUlRUcnV1akFvN0Y1bEJiTGsxTDJWMGNwNm5vQlJOaE9tRjQvSlpDWTBwYwp0eWtJSHNEMjN6K0NLVjRGdnE1ZVdwNzMyemlxNjFqLytqVmZpUDBsSTVvOFBISkFmVmNROHBPMFdQaVFQYU45CjFZZFZ4d0hKVjhzeDVyZnhQWHdObUo2OEZvd084N3U4WkpKcHVYY3duVlZRL1VNd1d0bG03eHBOMFRZem5kOG4KaVBnMC9xRWlBR1B3Ulk3dmcxWWs5V2wwemlqd1FHSGdBZzc2R0YyNVBLR0pUcmVDbFpHbGM4RE1XTGVhTVhmUQpDZmVJWnhwdlRpNnY5a25Dc01aMVZOQmV1VlVwQUppRHVFTmo4OCtoNFMrRnFoR3ZKV29vSDdhUktnOGI0R2tQClk4ZEZVQXJJUko4VmlUR01NNjYzdFVEV2tkM2hLV084K2Z5UTFDeGEyUXFJTDF4Z01YQlY0akdTZUtmNWdEeUUKdlNxc1c1TnFyeVdkblhMaFJOaDVmSkNuRzN3VEFiVE8wbVRHN2NjV0hDSnJsRktzRVlFTXVpVWUyNnFac3oyTQp0UjNDWVpwLzhnWkFLVTM1TzBQZzRyaGFIYk5QMlNKbEpmT0pPNnZOc0c5bExscDRxb3JVVURkYTVPUUxUSEwrCjBibExqOG1NWmIwV0lhZlNxQVFhU25ZbWllVVZTT3dTaFc1L3p6Qnl4VUxBMnZGSE56YUU0TElrOGhNQ0F3RUEKQVFLQ0FnRUFudUJxbjBLOWM5ekhudCs0bElnUEhKejB3TFYvV21Td0NHaXpvZ1RuNmRVTUhZd09xb2RwL1FCVgpST2tub1c4cUNDQ0VSL3I0R0V6K3hVSnpUMHBpSUtLd3R2OHVTUnNYcHcxWXZXaE52RkRDbThFTW5YV2Jyc05wCmg1TGJZOXlTR3dPbHJLQ0xQUlExWUFVam43bzY4cTZxVW5ubFFRb2dtdXRSSEVwVFpXM3k2WjJpank1aDU2cFIKZUlnYXY1Tkk4aFNleisyMWR0aTd3VFJubG1oWXV3eUdSKzNRSnhUd1QxVytDSXZsOEF3MnAvL2FwM29paTdBOQoralk0N01HM2hhdXBRaHh0dm9TV29CeDZGRnhSOTUrY0hGSmZ5WHgxdytzWkdQUW00RS84ekYwbnZMa1lQejEyCmg0TDlwbER5bW1KL21KUnQzSDB2TjN4MGUyT1BBT1hUNXpReExtQ3dEWEVmTlFUai95ZmVWS2U1SG5ybWNJMVkKS2hWdXo4L2szZ3RQVW9BellUOWYrTkpqQVFic1h6TExKTE9vU2RuZ1IyaFFkM1R5OWg5QmZzMGdkWVNKZzlTNQovT2NENWNqZUJ4RHVIU0pCaXZ1VmVCWGpwZHIzYTlDMEQwRUZHYXhDQlpkaGxVNmJPcHFwTUo3VG4xV1o5K0owCmZoWGV2L0srTmo5a1hwUnhOdHZJMWx4NndmamJ4dVFaTUtpd2FSZ0YxSWxqYW1PK280eHdGYnVlMnl4TWRIYXYKMExpdWhHMlVockZSR1cydGRvd25YS0h0Z091QS9HZWRsOEhwd2JEaE9YRzZZZWZZUTZQRzJPNzhLK211MTRycwpZM05KRTM4MURFUGFmMkdzQk5nUDgyL1VYbnBEVkU4MXdtclZWQU9nVTBVNEJwUW1qNEVDZ2dFQkFPUC90QW1ICmxsRXpMWHFwM280UkxiaytiMzh3Ky9yZXNhZFIrVTZSVWJoakRHT25XVFExcU12R25BRVM0djAwY2pZdGptRVgKZmJGRzFnWVNkYmNwV040cGxjR29uUVFNTkY3OHdNQTRZeXJDaHdXTkpqQmh4WDc0ZnpKaWhjRFB1N2NEa1dlWApqWkRFdWJkcjdTa2ZBVlFnWVAzeVNmZzFvVlp1U1dXZVcyU3hjalRPUXFPdTBnWlRGamp1dWJtYUlPaWpxWS80CmQ3bVl5TVJ1UjFsclAwWHhqeTNxY3p3NUxSU3p3WTFCMEFkUFk0dHdjRVBKaTJ6bHNGVCtleUQ0eUc4UVhwLzUKR0k0K2dlUCszWnVmTC9xMmVobzhQN2ZWbDcwdzN0eXczMndqaGpIcEtHSm10NFRhVFNhckVwbEwzOFBFdXBWcgpBM3VNdFpCNG1FV1hrVmNDZ2dFQkFNY25GMktwdVhBbnRxWmg2Z1owaWdzalUyeFE0WVlHcXRQYVVQcUdjWC9GCkxBYUJZWHRYVVh2cHBnZHlKTmUrdWFHa2dTUXlDZ25ZQXlrWGFNNHJhaUFxNHZuZ2x3UDZOSmFHQTJtajhxL24KSG9sQnpVMEdrVnJLVEJhVUxPNC9XMFFtcGM4V2VQakZDM1pSaEJHRThHM2JjZllQQVJPbktWVnNMRFlSY1pDYQpIbXlTTDdORWtmZlBNT0sza0lZMGFCMjdSVWZiV0pFT1dGNlpWcVZKWWlkUFR6TXl6SXJwMXFuSVAremtJRnVPCmVRTVFMcVA3R1BkZXYza2p6OE5xUDlpajdMWFBBamIzNWdFK2NQNXJOUnBvQmhmcS9kbTJiei9EZnpQdURqY3UKYTFMbElxYnNHWWNBODRuc1BFYVR6NGJlOGk4VXJZNTZ0QUJKTnJmWnc2VUNnZ0VBWFB3a0NON3JSeUtBSWM2MQpuV3NVSXNCNzZIdXB5SjZhQll0QkNmSHFTakRiRktsamtBOXlUK2tvSnFmMU94N3dsWGZ1NFZvYlFQbUt2OTgzCmN3UEI0cGxESWtBS0NXU1ExMHh0ci9kUE9sa3JoL0FRNnhwMDJWdXZSSFU1NTNEUk5jcVd1cERzZzJZMzk3NWsKY3FqYWVkemFzYmJtdy92YldNeVIwb2ZLN2o0UVBja0JGSkJ2eDNTTFU1ekkwaEV4NnE4VXNFcTlTVXd1VlM1RQptd3RLT3RSUmVJQnRqdG9pc0phL0VVVU4rbTArUTlnUGNSWDVidWdlQ2d2Zlc0c2E4M0RScHB5SWp6cWU3c1U2CnpBVVlKRC9YZkd1bDhPdURmdjAzWnZvYnBKYTRYQktqRGI2bWllQWVKdThPSHNiNjgzU0FRLy9vNDdKM09meDAKM2F6NjhRS0NBUUIreC9NS08xUXpBd1V5N0pob0haNlhzcGgwRnhWTEZrbC83cmFvbGhnQktBdDc1TGVqSnBaWQpGUWsrS2pzc0lWM1plbmxBQ3A3N1gwbTd5Z3hOVzdRRzRHWjRmcktFdEs3dnVFYko1TFlscHpONFc2eVB3WU9kClViV1lsaUg0VmRzTENyTjVueXZKNnQ3K0pxeTEzblNVNnlPa2FpN2NUUWx5T1JmNEg2aTFUbmZaMUVLTGxEWjgKbEtqaFc4eWtzdzRwQjBQMmw3dk5ORjJyYzJDR2ZxMytxbTJZQVZuWGdUL0gvQlErQVloYjROcEd5ZkYzTU8zVwo1TGx1TEE4aXJ5d1FCV00yNXA3WlVYMWFBMTg1aUJSWlNDbkE1amRPZHVaaHFGbjlQQ3BPbEwxOEd5U3hNUktiCk1FN1oyY3NSZngyWkZhc0ZyOXRCSGZvalNIaU9HQktGQW9JQkFHYUU3NENzaHpTTk8zb1NkWmx1dEdMeW1XVG0KS0w0Nm9yd1hIcWZ6ZUNBQjM4NmFEcEYrYnViSWtPQ2w4M0YrWWU2QXhJTFV6bjBPUHVBZjVrNjBRdStXc2EvdApuRTNYeE8zTFI0MFBLQ3JINDExaEhkMW5lMU8yd2NRK2pQTld0MmVhMmFneDBNamo5cy9FQmNqTXpjNWJTNm5rCmE4K2d1akVXWTdOQkROZU1waWxzcVhTaU5PbGcyQ1JkK0dndWJ6TmhIazM5UGRnRU1rVmpxVnBNQUVhMG82STkKSUdTU3NMYnp1QnkzeWhjMTR2T05FNTFPT1BZUmR4Y3JvUmE4akJXRjNXakJyZytjOGlPeDl5cmRnN0h3NFlMVwpmTC9Yb1k0NWJldXdjUTEwV1BHNEZUUGVSTUhrV3U2S1FZdjJNQndrNkJIT1JDTVVMR2NjK2VXbFhRUT0KLS0tLS1FTkQgUlNBIFBSSVZBVEUgS0VZLS0tLS0K
  apiServer:
    image: registry.k8s.io/kube-apiserver:v1.32.0
    certSANs:
      - 192.168.2.20
      - 192.168.2.20
      - master01.local
      - 127.0.0.1
    disablePodSecurityPolicy: true
    auditPolicy:
      apiVersion: audit.k8s.io/v1
      kind: Policy
      rules:
        - level: Metadata
  controllerManager:
    image: registry.k8s.io/kube-controller-manager:v1.32.0
  proxy:
    disabled: true
    image: registry.k8s.io/kube-proxy:v1.32.0
  scheduler:
    image: registry.k8s.io/kube-scheduler:v1.32.0
  discovery:
    enabled: true
    registries:
      kubernetes:
        disabled: true
      service:
        disabled: false
  etcd:
    ca:
      crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJmakNDQVNTZ0F3SUJBZ0lSQUoxMmFPWjdPYkc5dTY1SkZUbUJNam93Q2dZSUtvWkl6ajBFQXdJd0R6RU4KTUFzR0ExVUVDaE1FWlhSalpEQWVGdzB5TkRFeU16RXlNRE0xTVRKYUZ3MHpOREV5TWpreU1ETTFNVEphTUE4eApEVEFMQmdOVkJBb1RCR1YwWTJRd1dUQVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05DQUFSVDBwZTUrbWkyCndpZi9XWFFkR1lWS1BjVk1RbWZKdTJJcDk1SVBqMTZjVDZYOFV2WlVFZWViNU45d3NFSDYrd1Q4amRJcGJjMmwKV0ROSDNwODJZUDVrbzJFd1h6QU9CZ05WSFE4QkFmOEVCQU1DQW9Rd0hRWURWUjBsQkJZd0ZBWUlLd1lCQlFVSApBd0VHQ0NzR0FRVUZCd01DTUE4R0ExVWRFd0VCL3dRRk1BTUJBZjh3SFFZRFZSME9CQllFRkZIZmxiTXJkMVJVCnUyb3k3T1p4V0huNlBMQjdNQW9HQ0NxR1NNNDlCQU1DQTBnQU1FVUNJQzJEK08yQm5pYnNCWmJ3STUvYzRaZC8KN1crc2phcUNHblhYbXMrazJSdzZBaUVBOCsxZVZoOWc2T0dtOFArRWUvMzN1R0ZqclFRc1VJeEQ3Nmh5UUptdwpWTTg9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      key: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUNoMG9mT2FQOE0rTmdieXQvd3F6RlVMSjV4TUorU2hNVk1xUWIxLzdFcWFvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFVTlLWHVmcG90c0luLzFsMEhSbUZTajNGVEVKbnlidGlLZmVTRDQ5ZW5FK2wvRkwyVkJIbgptK1RmY0xCQit2c0UvSTNTS1czTnBWZ3pSOTZmTm1EK1pBPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
    advertisedSubnets:
      - 192.168.2.0/24
      - 192.168.1.0/24
  coreDNS:
    disabled: true
  allowSchedulingOnMasters: true
  allowSchedulingOnControlPlanes: true
