---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: npm
    directory: "/docs"
    schedule:
      interval: "weekly"
  - package-ecosystem: gomod
    directories:
      - "/"
    schedule:
      interval: weekly
    ignore:
      - dependency-name: "github.com/teaglebuilt/homelab"
