---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ai
resources:
  - vllm-pv.yaml
  - vllm-pvc.yaml
  - deployment.yaml
  - service.yaml
  - backend.yaml
  - httproute.yaml
  - modelconfig.yaml
  - agent.yaml
generators:
  - secrets-generator.yaml
