apiVersion: ENC[AES256_GCM,data:Fn0=,iv:hfGiKJvapAnUPt/kiyLgF5/oXtSnkln2BGP22JtEuHE=,tag:Xo3YpH4yKWLqQlrIAyzmPg==,type:str]
kind: ENC[AES256_GCM,data:fGL5zsON,iv:SDv0AsBh6/Wy/oM0nA0g24MNhbOU6l0Pa/AkPKpxNXI=,tag:YK9uU+WFhCDuqF2LPkw8bA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:EcqpELIy+nrTWCOlJ9CMF7R6,iv:k0DhPs87s/A2PGz84AiYJx1JMYqsMeDU9hHuAA8WiMw=,tag:zaUp02EKtM8wh0uKtPxMFQ==,type:str]
    namespace: ENC[AES256_GCM,data:mqVql20Q,iv:x7UrgWvFFzONO7kb6FQB+FrhrsBCcCUfsSZXuxq9GCo=,tag:fVcckVTZU94oBGatQfFKBQ==,type:str]
type: ENC[AES256_GCM,data:DSTjq77D,iv:xnz6tiGbvZ/amufqV9epCCwExBDhWNu1q3BX+WjOrIo=,tag:2F8Yd52OcFwyOamjO9ZGTQ==,type:str]
stringData:
    api-key: ENC[AES256_GCM,data:B7KE228afle19g==,iv:bUoTt/KpHkKNFOvzpNsAYaAVJp8AWvR0lSrDhDkO324=,tag:cr79LSKlZpZ5/ImFgOPNhw==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:626956831217:key/f22ea8b8-ec28-4d80-988e-7372419dbc28
          created_at: "2026-07-22T21:14:38Z"
          enc: AQICAHgf2Bz/yC/N+d80dqtXyzpCypiaZx1Lgwl8YcJR1TYnOAG6dbqE5eeo5hnELBpSH4CkAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMQEqI8pTb89xGCJgHAgEQgDtu6lKCZ4pxCyfHx1ZTmkd1INWgd2VZKssn9vwhtiZRAIukzcH7A7rB3cStoFEuba86pqEKa5j2C2U4FA==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-07-22T21:14:38Z"
    mac: ENC[AES256_GCM,data:vVEK7SLW4q/BkDilRNNWTxe/bXeYDlEo+fcLygFvMlRuQncWcrdEOeUYoh54Yvz/nj0I5VsZVBnP91pSCTmg4KKDmuyG0ACt9Z2R0lxdh9sWY4ldzu8EBwGuBEQrQJ8QyF5tX8dR6Hdk9P6K8D8QHVB/7AC7F+lwSTwS4t5LBbI=,iv:Xle3J+CldVbjQ9NeH8wIuDveHyJe0xl/sAJmW9eELIw=,tag:6QcScD5glELPCerYkednQw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|apiVersion|metadata|kind|type)$
    version: 3.8.1
