creation_rules:
  - path_regex: homelab\.sops\.env$
    kms: "arn:aws:kms:us-east-1:007501151094:key/1e9daac7-acca-43cf-bc21-199ad2b92deb8"
  - path_regex: kubernetes/*
    encrypted_regex: "^(data|stringData|apiVersion|metadata|kind|type)$"
    kms: "arn:aws:kms:us-east-1:007501151094:key/1e9daac7-acca-43cf-bc21-199ad2b92deb8"
  - path_regex: platform/*
    encrypted_regex: "^(data|stringData|apiVersion|metadata|kind|type)$"
    kms: "arn:aws:kms:us-east-1:007501151094:key/1e9daac7-acca-43cf-bc21-199ad2b92deb8"
  - path_regex: machines/.*
    kms: "arn:aws:kms:us-east-1:007501151094:key/1e9daac7-acca-43cf-bc21-199ad2b92deb"
