version: '3'

set: [pipefail]
shopt: [globstar]

includes:
  kubernetes:
    taskfile: kubernetes/Taskfile.yml
  containers:
    taskfile: containers/Taskfile.yml
  network:
    taskfile: rack/network/Taskfile.yml
  platform:
    taskfile: platform/Taskfile.yml
  machines:
    dir: machines
    taskfile: machines/Taskfile.yml

dotenv: [
  './kubernetes/.env',
  './containers/.env',
  './platform/observability/.env',
]

tasks:
  help:
    silent: true
    cmds: [ "task -l" ]

  default:
    silent: true
    cmd: task --list

  noop:
    internal: true
    silent: true
    cmd: noop() { :; }

  deploy-homelab:
    cmds:
      - task: kubernetes:provision-administration
      - task: kubernetes:provision-mlops
      - task: kubernetes:bootstrap-cluster
        vars: { CLUSTER: mlops }
      - task: kubernetes:bootstrap-cluster
        vars: { CLUSTER: administration }
      - task: kubernetes:connect-clusters
      - task: kubernetes:wait-for-external-certificate
      # - task: kubernetes:copy-kubeconfig
      - task: platform:deploy
      - task: platform:test

  spin-up-*:
    summary: Used for launching any platform service locally.
    vars:
      STACK: '{{index .MATCH 0}}'
    cmds:
      - echo "Starting stack [{{.STACK}}]"
      - docker compose up -d platform/{{.STACK}}

  serve-docs:
    cmds:
      - task: docs:serve
