version: '3'

set: [pipefail]
shopt: [globstar]

includes:
  kubernetes:
    taskfile: kubernetes/Taskfile.yml
  containers:
    taskfile: containers/Taskfile.yml
  platform:
    taskfile: platform/Taskfile.yml
  docs:
    taskfile: docs/Taskfile.yml

dotenv: ['./kubernetes/.env']

tasks:
  help:
    silent: true
    cmds: [ "task -l" ]

  default:
    silent: true
    cmd: task --list

  noop:
    internal: true
    silent: true
    cmd: noop() { :; }

  deploy-mlops-cluster:
    summary: Standup kubernetes cluster and platform services
    cmds:
      - task: kubernetes:provision-cluster
      - task: kubernetes:cluster-health
        vars: { CONTROL_PLANE: $MASTER_NODE_IP}
      - task: kubernetes:bootstrap-cluster
      - task: kubernetes:sync-cluster
      - task: kubernetes:test-cluster
      - task: platform:deploy

  spin-up-*:
    summary: Used for launching any platform service locally.
    vars:
      STACK: '{{index .MATCH 0}}'
    cmds:
      - echo "Starting stack [{{.STACK}}]"
      - docker compose up -d platform/{{.STACK}}

  serve-docs:
    cmds:
      - task: docs:serve
