---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-mesh
  namespace: observability
  labels:
    app.kubernetes.io/name: prometheus-mesh
    app.kubernetes.io/part-of: homelab
  annotations:
    service.cilium.io/global: "true"
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: prometheus
    operator.prometheus.io/name: prometheus-community-kube-prometheus
  ports:
    - name: http-web
      port: 9090
      targetPort: 9090
      protocol: TCP
