apiVersion: ENC[AES256_GCM,data:138=,iv:0GFVhKBu52Vit6r0naiDZ8TZJU4HPyKpM+Bl6weL5+Y=,tag:MIVtNSJ7lXYg6HslnsLZ/A==,type:str]
kind: ENC[AES256_GCM,data:g2DMR9mo,iv:qBf1CIeXsphHDV/BGehmtu/efSA11ieCDXsHt8Ynbtc=,tag:7KRyeptomsuUJLopfieSmw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:DnESLnU+QajGXz9O9hDDl+1HQ6Ig,iv:tNLdEXkkChcgoC6qkrkDh+6AzcOeCU5IFPnPhx9cf1w=,tag:HMghyz/JDjxpWkUToClT0A==,type:str]
    namespace: ENC[AES256_GCM,data:UR0=,iv:T7YzOoWD5u288MUg8SLE+K8vqwtkxUS7gIvu2wd2Q5U=,tag:Ku9HDelNIvWNMYT9Kipz1g==,type:str]
type: ENC[AES256_GCM,data:GsQyBUbG,iv:JPL+l6vazjGPsyf8+UgXCg9yOGa7v1M8tqnhmZlWWXQ=,tag:E2jDMW2HsviYacXmaJ1pXw==,type:str]
stringData:
    Authorization: ENC[AES256_GCM,data:HjgFMymJNU5rJDB2oyDwSmTlixSAAZL7URbn4DhgHQ2qHXlRBGjrpGS9+z4F0NelE75tWPsK0gp14l5W/iVIRXhNSfjLitWMIBKDj8Qt0K+aHfVvZ+Sg0tJ4pByZ7eGhjVHmto0Dt+1fC/j6yIK+jgg3hu28LRlILVpFYgqjLxR+19JWe/jMEASIudF6Fm9fXKUvFsLJH+B9YdnPcHfg5F+Ac4k=,iv:cVC8ZU5zQvigul179F6JI5jBqzeQ1y4D7xExeyf6udk=,tag:ECn2M3pJQJ4fFE9tqFssZg==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:626956831217:key/f22ea8b8-ec28-4d80-988e-7372419dbc28
          created_at: "2026-07-31T21:38:53Z"
          enc: AQICAHgf2Bz/yC/N+d80dqtXyzpCypiaZx1Lgwl8YcJR1TYnOAHbT6wE7EtZxz2uIUy9fyE/AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMruH42FoNu2/FOZaNAgEQgDuVTbqNG6aSIpsIu4JH9XX6XvahtyikbsUFCJCPxcdYNzMnIiXuPZPJpDi2rKaXIlk9EAjR/rTG5XiKKA==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-07-31T21:38:53Z"
    mac: ENC[AES256_GCM,data:RzckQ+HNV11RsVAXnOYydrILiStcy39KmkTaqmfPSoIMeYfqZOyd6eJ9NciB5BJxLjUw3dnq1Si6AIlvS6zcl+jMy1cJN+EZfF1TfJee1y7cuDHuUQ2YwZD/NArn4HFYj5rgtOggjDTrd1Y7Lv+Q5K02dYuH+VmhdAmuTEeKVKM=,iv:9XeHaiU1e1IJYXRt+u6GxWC8kZTgvKJ45PrOpGgy4is=,tag:R+TZMEEhWrv20tCFP2PoFw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|apiVersion|metadata|kind|type)$
    version: 3.8.1
