apiVersion: ENC[AES256_GCM,data:eJM=,iv:MgZdfoQCwJJNQObxVDPJoSKQDo8wISS/Bcx/abk4eLQ=,tag:g8dugblytFTFCjQkOG6KlA==,type:str]
kind: ENC[AES256_GCM,data:KYifH0vZ,iv:bX9Bcar6xhrAdY/xGQZbYVYOPsACJ2Xq/e3VA9R6aJE=,tag:fxKa+c5Cy94BJrzUNfCSww==,type:str]
metadata:
    name: ENC[AES256_GCM,data:nejIe3tLZAOMYhq58mZvhzB5Rd8c,iv:BFa+O9DRskMkTfkWoEpnVYa/pDmvr4UJCuuAECDpuv0=,tag:Rc/bKloYGzrws76zDpTq3A==,type:str]
    namespace: ENC[AES256_GCM,data:9MA=,iv:5mPYhCFRPu8upxY658/U/ZTM5R/+h7Qa6lI61rL53+M=,tag:C9h1kJTKR1HBVluS/BEhfQ==,type:str]
type: ENC[AES256_GCM,data:ocTnD/wK,iv:BTr+SI1G7MlWO+Z4ueG6VeGdjHfVTllSZPPJOQZkeR4=,tag:HEJwJ4aQgUGJ7UH+J3JgFQ==,type:str]
stringData:
    Authorization: ENC[AES256_GCM,data:VcynRpvfWtskxVjxSW/NzaVKMnDnWq/Y0fbQMloixu3IkLXFik9w/JyR0qHqKhgev1R1fGaN2l+PkVEHqdOIchBa3EIZ+1KBwT3e2swWeR8JZ0dYSS0BP53jCLSky+bC8PSRVYo6VNp4cp07PJjb/S2FF5kfqt/EHtKiz9ivQrbnlwyLIBfgxmZkl7NweAjUIdD4LDO4Zgnv0HqM7UifaKzU5CA=,iv:xdEcW5gJVoRFB4uo1KHPurSs1g3CizbfuuR8tFE+r4c=,tag:/+bYnBRdDnD5eKZ5ffHf3Q==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:626956831217:key/f22ea8b8-ec28-4d80-988e-7372419dbc28
          created_at: "2026-05-19T20:50:16Z"
          enc: AQICAHgf2Bz/yC/N+d80dqtXyzpCypiaZx1Lgwl8YcJR1TYnOAF74gDhdWxpX09WVXCKFmI3AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMAx+joZ0ftsf1gUEnAgEQgDvUJGwyI1mRBRcHS7wQxBETUps9M8rZRj/0d7VMSy8eQdHgWV8IfhkfM6/Ilf9Dl1zWPeJYI2COmATEGw==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-05-19T20:50:16Z"
    mac: ENC[AES256_GCM,data:j58OlwcAH2SKuIKKTtawHvlj1QcRFQCBo+suLjpU9LSDBSNYaOi6pK/fvKjU0jVlPrvHPCqwcK37RcqyuaJWCZ/NTJ3hhMEg7F3QpQNQbv2+81BUrzcNisQyDZNqgajm/TnaUpTnl2XwwlVgp/1aE/aLljUa9x6Ge7rArGmenz0=,iv:LZcCCLSKbtVbq1qOV7xXmH9HFXAMs7VNiFBQVj/W/es=,tag:eN+6zb6psoE2q4VtWCR8qg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|apiVersion|metadata|kind|type)$
    version: 3.8.1
