apiVersion: ENC[AES256_GCM,data:b1I=,iv:nUrFlhV05obskv86eazc1p11Krb7flD7zq761c91QYA=,tag:lzJzlRDWu83+cXSrVUelYw==,type:str]
kind: ENC[AES256_GCM,data:CzIDz6AN,iv:ZOEYJ7mVXpyn1Z87zQsgpKmCQNNzTPP8VgT/Eh/XlpA=,tag:SY7m9JmbOINzwPMpMDOIkg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:gLJOdLQjaGnBFJ9Jrwx/DWfxMLYO,iv:baL/gjcBoZZB2kfir4J+CGC4+9ka/zKmmeJobwITs2c=,tag:2unw7igcb3itph4NnSAzIg==,type:str]
    namespace: ENC[AES256_GCM,data:5mA=,iv:J+cPCTH2K3/dKq0IgCsFFKygIc6/s2C76zpjBUfhrOU=,tag:9UiTNYReTGenS0xiASFMNg==,type:str]
type: ENC[AES256_GCM,data:BFzsA7th,iv:HBmdxz+pOR1+VdpGEGMi40PL+31b9IafgBogHWjtkLM=,tag:G/Kmm/acXwF3j33j87+L4g==,type:str]
stringData:
    Authorization: ENC[AES256_GCM,data:OfU/w0iDUicAxj09SCWBNTeNofyroWoRl/Ei/B70YQwhRuLFhtgVI9yCaBzpvPWk/yFFD0LWQLFDDafW8EzX1eMYPY+9PL+WTNyEEFjK5BmBIS6fLYvQxqC5WeUbzG1tKt3pf2H5pf/+lEWT5dz6cEb82DPtiZ9Dc9WD7E9EDsIstzctxsn5moTypSqaNi8UKpA06u0JBJ1FRPFKnCoOc+JDkXI=,iv:gb1G4V4Gab2olNGnp2Cqv2+5I9zbdTWqxvgpEUyuRXg=,tag:cAnV3jl6ypxgPqoHbLJdRw==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:626956831217:key/f22ea8b8-ec28-4d80-988e-7372419dbc28
          created_at: "2026-04-25T20:32:41Z"
          enc: AQICAHgf2Bz/yC/N+d80dqtXyzpCypiaZx1Lgwl8YcJR1TYnOAEWcnvgzkrVbkCN9Qj518FTAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMIFirTI9NYD0fgBxrAgEQgDttFo6av9UrEqbTrijLJLaMr2baxlAqF10hOQS2fpxZCdxJl15mtYS139vWggl/+amIRcvOMx5j97ZUPQ==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-04-25T20:32:41Z"
    mac: ENC[AES256_GCM,data:1ueYKsxzgAMvztWqSLoHpe8Z54rSDQw/FEa1NBjXUCC6gKDGGakZOCrfk/7EAl/hxDB+zTl9PGy3rsyXNFf54mzYJ1yb37EWGvcI4c9SqkG//6DgXDFfDZYGoiUXqRs0Z26DXuY7Haoc8OrAJbAoK7TiLo1nEKE19MIWUXFwXZ8=,iv:/sH3OeVqyo3gMX0huHhMKzRK5Bfd7oV+GvJYpp0oMUk=,tag:YqyipN1kj+FkbLaXWx7Cwg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|apiVersion|metadata|kind|type)$
    version: 3.8.1
