---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: lets-encrypt-prod
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: dillan.teagle.va@gmail.com
    privateKeySecretRef:
      name: lets-encrypt-prod-secret
    solvers:
      - http01:
          ingress:
            class: nginx
