---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-dns
spec:
  acme:
    email: "dillan.teagle.va@gmail.com"
    server: "https://acme-v02.api.letsencrypt.org/directory"
    privateKeySecretRef:
      name: letsencrypt-dns
    solvers:
    - dns01:
        webhook:
          groupName: "acme.example.com"
          solverName: "unifi"
          config:
            apiUrl: "https://unifi.example.com"
            username: "admin"
            passwordSecretRef:
              name: unifi-dns-creds
              key: password