---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: homelab-ca
  namespace: cert-manager
spec:
  secretName: homelab-ca-secret
  commonName: homelab-ca
  isCA: true
  issuerRef:
    name: selfsigned-cluster-issuer
    kind: ClusterIssuer