---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: n8n-cert
spec:
  secretName: n8n-tls
  issuerRef:
    name: letsencrypt-dns
    kind: ClusterIssuer
  dnsNames:
  - n8n.homelab.local