---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: n8n
  namespace: automation
  labels:
    app: n8n
    version: v1.0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: n8n
  template:
    metadata:
      labels:
        app: n8n
        version: v1.0
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      initContainers:
        - name: n8n-import
          image: ghcr.io/n8n-io/n8n:1.76.0
          command: ["/bin/sh", "-c"]
          args:
            - |
              n8n import:credentials --separate --input=/backup/credentials
              n8n import:workflow --separate --input=/backup/workflows
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
            seccompProfile:
              type: RuntimeDefault
          volumeMounts:
            - name: credentials
              mountPath: /backup/credentials
            - name: workflows
              mountPath: /backup/workflow
      containers:
        - name: n8n
          image: ghcr.io/n8n-io/n8n:1.76.0
          ports:
            - containerPort: 5678
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
            seccompProfile:
              type: RuntimeDefault
          resources:
            requests:
              cpu: 150m
              memory: 512Mi
            limits:
              cpu: 550m
              memory: 768Mi
          env:
            - name: N8N_SECURE_COOKIE
              value: "false"
            - name: N8N_HOST
              value: n8n.homelab.local
            - name: N8N_PROTOCOL
              value: https
            - name: N8N_SSL_CERT
              value: "/certs/tls.crt"
            - name: N8N_SSL_KEY
              value: "/certs/tls.key"
            - name: N8N_DIAGNOSTICS_ENABLED
              value: "false"
            - name: N8N_ONBOARDING_FLOW_DISABLED
              value: "true"
            - name: N8N_VERSION_NOTIFICATIONS_ENABLED
              value: "false"
            - name: N8N_EXTERNAL_STORAGE_HOST
              value: "s3.us-east-1.amazonaws.com"
            - name: N8N_EXTERNAL_STORAGE_S3_BUCKET_NAME
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: aws_homelab_remote_state_backup
            - name: N8N_EXTERNAL_STORAGE_S3_BUCKET_REGION
              value: "us-east-1"
            - name: N8N_EXTERNAL_STORAGE_S3_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: aws_access_key_id
            - name: N8N_EXTERNAL_STORAGE_S3_ACCESS_SECRET
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: aws_secret_access_key

          volumeMounts:
            - name: credentials
              mountPath: /backup/credentials
            - name: certificates
              mountPath: "/certs"
              readOnly: true
            - name: workflows
              mountPath: /backup/workflows
            - name: n8n-storage
              mountPath: /home/node/.n8n
      volumes:
        - name: credentials
          configMap:
            name: credentials-cm
        - name: certificates
          secret:
            secretName: n8n-tls
        - name: workflows
          configMap:
            name: workflows-cm
        - name: n8n-storage
          persistentVolumeClaim:
            claimName: n8n-storage-pvc
  