---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: automation
resources:
  - deployment.yaml
  - service.yaml
  - configmap.yaml
  - pvc.yaml
  - ingress.yaml

configMapGenerator:
  - name: workflows-cm
    files:
      - srOnR8PAY3u4RSwb.json=workflows/demo-workflow.json
      - srOnR8PAY3u4RSrb.json=workflows/backup-workflows.json
  - name: credentials-cm
    files:
      - sFfERYppMeBnFNeA.json=credentials/ollama.json
      - sFfERYppMeBnFNeB.json=credentials/qdrant.json

generatorOptions:
  disableNameSuffixHash: true