apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: n8n-storage-pvc
  namespace: automation
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: nfs-csi
  volumeName: automation-platform-storage
  resources:
    requests:
      storage: 15Gi
