apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: n8n-storage-shared-pvc
  namespace: automation
  labels:
    version: v1.0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
