---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
resources:
  - runtimeclass.yaml
  - priorityclass.yaml
  - recovery-rbac.yaml
  - recovery-configmap.yaml
  - recovery-daemonset.yaml
  - xid-alerts.yaml
configMapGenerator:
  - name: gpu-recovery-scripts
    files:
      - scripts/recover.sh
      - scripts/watch.sh
generatorOptions:
  disableNameSuffixHash: false
