---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: homelab-cert
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
spec:
  secretName: homelab-tls
  dnsNames:
    - homelab.internal
    - "*.homelab.internal"
  issuerRef:
    name: internal-ca-cluster-issuer
    kind: ClusterIssuer
