---
{{- if .Values.external.tunnelHostnames }}
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: cloudflare-dns
  namespace: kube-system
spec:
  endpoints:
    {{- range .Values.external.tunnelHostnames }}
    - dnsName: "{{ . }}.{{ $.Values.external.domain }}"
      recordType: CNAME
      targets:
        - {{ $.Values.external.tunnel_id }}.cfargotunnel.com
    {{- end }}
{{- end }}
