---
{{- if and .Values.external.publicGateway .Values.external.tunnelHostnames }}
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: homelab-external-gateway
  namespace: kube-system
spec:
  gatewayClassName: cilium
  {{- with .Values.external.loadBalancerIP }}
  infrastructure:
    annotations:
      io.cilium/lb-ipam-ips: {{ . | quote }}
  {{- end }}
  listeners:
    {{- range .Values.external.tunnelHostnames }}
    - name: https-{{ . }}
      protocol: HTTPS
      port: 443
      hostname: "{{ . }}.{{ $.Values.external.domain }}"
      allowedRoutes:
        namespaces:
          from: Selector
          selector:
            matchLabels:
              homelab.io/public-ingress: "true"
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: external-cloudflare-tls
    {{- end }}
{{- end }}
