---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: homelab-gateway
  namespace: kube-system
spec:
  gatewayClassName: envoy
  listeners:
  - name: https
    port: 443
    protocol: HTTPS
    hostname: "*.homelab.internal"
    tls:
      certificateRefs:
      - kind: Secret
        group: ""
        name: homelab-tls
    allowedRoutes:
      namespaces:
        from: All
