---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: hubble-ui-route
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
    external-dns.alpha.kubernetes.io/hostname: hubble.homelab.internal
spec:
  parentRefs:
    - name: homelab-gateway
  hostnames:
    - hubble.homelab.internal
  rules:
    - matches:
      - path:
          type: PathPrefix
          value: "/"
      backendRefs:
      - name: hubble-ui
        port: 80
    # - matches:
    #   - path:
    #       type: PathPrefix
    #       value: "/metrics"
    #   backendRefs:
    #   - name: hubble-metrics
    #     port: 9965
