---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - httproute.yaml
helmCharts:
  - name: open-webui
    repo: https://helm.openwebui.com/
    version: 6.0.0
    namespace: ai
    releaseName: open-webui
    valuesFile: values.yaml

generators:
  - secrets-generator.yaml
