---
machine:
  install:
    extraKernelArgs:
      - cpufreq.default_governor=performance
      - intel_iommu=on
      - intel_pstate=disable
      - iommu=pt
      - mitigations=off
      - net.ifnames=0
      # - talos.logging.kernel=udp://vector.${INTERNAL_DOMAIN}:6001/
    legacyBIOSSupport: true