---
# Production Docker Compose Configuration for Portainer Stack
# This file uses pinned versions and security best practices
# DO NOT use :latest tags in production

version: '3.8'

services:
  portainer:
    # Pinned to specific version instead of :latest
    image: portainer/portainer-ce:2.21.4-alpine
    container_name: portainer
    restart: unless-stopped

    # Security: Read-only root filesystem with specific writable paths
    read_only: true
    tmpfs:
      - /tmp

    # Security: Drop all capabilities, add only required ones
    cap_drop:
      - ALL

    # Security: Run as non-root user (Portainer runs as UID 1000)
    user: "1000:1000"

    # Resource limits to prevent DoS
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 128M

    ports:
      - "8000:8000"   # Edge agent tunnel
      - "9443:9443"   # HTTPS UI
      - "9000:9000"   # HTTP UI (consider disabling in production)

    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock:ro  # Read-only socket

    environment:
      # Security: Enforce HTTPS
      - PORTAINER_TUNNEL_PORT=8000

    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:9000/api/system/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  homepage:
    # Pinned version
    image: ghcr.io/gethomepage/homepage:v0.9.11
    container_name: homepage
    restart: unless-stopped

    # Security: Read-only root filesystem
    read_only: true
    tmpfs:
      - /tmp
      - /app/config/logs

    # Security: Run as non-root user
    user: "1000:1000"

    # Resource limits
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 64M

    environment:
      PUID: 1000
      PGID: 1000
      # Security: Restrict allowed hosts
      HOMEPAGE_ALLOWED_HOSTS: "${HOMEPAGE_ALLOWED_HOSTS:-gethomepage.dev}"
      # Optional: Set timezone
      TZ: "${TZ:-UTC}"

    ports:
      - "3000:3000"

    volumes:
      - ./config:/app/config:ro  # Read-only config
      - /var/run/docker.sock:/var/run/docker.sock:ro

    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

    # Network security: Prevent access to metadata endpoints
    dns:
      - 1.1.1.1
      - 1.0.0.1

volumes:
  portainer_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/local/docker/portainer_data

# Security: Use custom bridge network with isolation
networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/16
