apiVersion: v2
appVersion: latest
description: The Helm chart for Envoy AI Gateway
home: https://aigateway.envoyproxy.io/
icon: https://raw.githubusercontent.com/envoyproxy/ai-gateway/refs/heads/main/site/static/img/logo.svg
keywords:
- gateway-api
- envoyproxy
- envoy-gateway
- eg
- ai-gateway
- ai
maintainers:
- name: envoy-ai-gateway-maintainers
  url: https://github.com/envoyproxy/ai-gateway/blob/main/CODEOWNERS
name: ai-gateway-helm
sources:
- https://github.com/envoyproxy/ai-gateway
type: application
version: v0.0.0-latest
