---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: n8n
  namespace: automation
  labels:
    app: n8n
    version: v1.0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: n8n
  template:
    metadata:
      labels:
        app: n8n
        version: v1.0
    spec:
      initContainers:
        - name: n8n-import
          image: n8nio/n8n:latest
          command:
            - /bin/sh
            - -c
            - "n8n import:credentials --separate --input=/backup/credentials --update-existing  --verbose ; n8n import:workflow --separate --input=/backup/workflows"
          volumeMounts:
            - name: credentials
              mountPath: /backup/credentials
            - name: workflows
              mountPath: /backup/workflow
      containers:
        - name: n8n
          image: n8nio/n8n:latest
          ports:
            - containerPort: 5678
          resources:   # Add resource requests and limits
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 2Gi
          volumeMounts:
            - name: n8n-storage
              mountPath: /home/node/.n8n
            - name: credentials
              mountPath: /backup/credentials
            - name: workflows
              mountPath: /backup/workflows
            - name: shared-data
              mountPath: /data/shared
        volumes:
          - name: n8n-storage
            persistentVolumeClaim:
              claimName: n8n-storage-pvc
          - name: credentials
            projected:
              sources:
                - configMap:
                    name: credentials-cm
                - configMap:
                    name: workflows-cm
          - name: workflows
            persistentVolumeClaim:
              claimName: n8n-storage-workflows-pvc
          - name: shared-data
            persistentVolumeClaim:
              claimName: n8n-storage-shared-pvc