---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: comfyui-ai-storage
  annotations:
    pv.kubernetes.io/provisioned-by: nfs.csi.k8s.io
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-csi
  mountOptions:
    - nolock
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: comfyui-ai-storage
    volumeAttributes:
      server: unas.internal
      share: /var/nfs/shared/ai_platform_data/integrations/comfyui
    readOnly: false
