---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ai
resources:
  - comfyui-pv.yaml
  - comfyui-pvc.yaml
  - deployment.yaml
  - service.yaml
  - httproute.yaml
  - mcp-server.yaml
  - mcp-service.yaml
  - configmap.yaml
configMapGenerator:
  - name: comfyui-scripts
    files:
      - scripts/download-data.sh
      - scripts/start-comfyui.sh
