---
apiVersion: api.kagent.dev/v1alpha3
kind: ModelConfig
metadata:
  name: bedrock-anthropic-claude-3-5-sonnet
  namespace: ai
spec:
  provider: OpenAI
  model: bedrock-claude-3-5-sonnet
  apiKeySecret: bedrock
  apiKeySecretKey: key
  openAI:
    baseUrl: http://litellm-service.default.svc.cluster.local:4000
