---
datasources:
  postgres:
    url: jdbc:postgresql://postgres:5432/kestra
    driverClassName: org.postgresql.Driver
    username: ${KESTRA_POSTGRES_USER}
    password: ${KESTRA_POSTGRES_PASSWORD}

kestra:
  plugins:
    configurations:
      - type: io.kestra.plugin.scripts.runner.docker.Docker
        values:
          volume-enabled: true
  url: http://localhost:8080/
  server:
    basicAuth:
      enabled: false
  repository:
    type: postgres
  storage:
    type: local
    local:
      base-path: "/app/storage"
  tasks:
    tmp-dir:
      path: /tmp/kestra-wd/tmp
  queue:
    type: postgres
