---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: research
resources:
  - deployment.yaml
  - service.yaml
  - internal-httproute.yaml
configMapGenerator:
  - name: searxng-settings
    files:
      - settings.yml
generators:
  - secrets-generator.yaml
