---
use_default_settings: true

general:
  instance_name: "homelab research"
  privacypolicy_url: false
  donation_url: false
  contact_url: false
  enable_metrics: true

search:
  safe_search: 0
  autocomplete: ""
  default_lang: "auto"
  formats:
    - html
    - json

server:
  port: 8080
  bind_address: "0.0.0.0"
  base_url: false
  limiter: false
  public_instance: false
  image_proxy: false

ui:
  static_use_hash: true

outgoing:
  request_timeout: 6.0
  max_request_timeout: 15.0
  pool_connections: 100
  pool_maxsize: 20
  enable_http2: true

engines:
  - name: duckduckgo private
    engine: duckduckgo
    shortcut: pddg
    categories: [private]
    disabled: false
    timeout: 20.0
    using_tor_proxy: true
    proxies:
      http:
        - socks5h://tegress.homelab.internal:9050
      https:
        - socks5h://tegress.homelab.internal:9050

  - name: mojeek private
    engine: mojeek
    shortcut: pmj
    categories: [private]
    disabled: false
    timeout: 20.0
    using_tor_proxy: true
    proxies:
      http:
        - socks5h://tegress.homelab.internal:9050
      https:
        - socks5h://tegress.homelab.internal:9050

  - name: startpage private
    engine: startpage
    shortcut: psp
    categories: [private]
    disabled: false
    timeout: 20.0
    using_tor_proxy: true
    proxies:
      http:
        - socks5h://tegress.homelab.internal:9050
      https:
        - socks5h://tegress.homelab.internal:9050

  - name: wikipedia private
    engine: wikipedia
    shortcut: pwp
    categories: [private]
    disabled: false
    timeout: 20.0
    using_tor_proxy: true
    proxies:
      http:
        - socks5h://tegress.homelab.internal:9050
      https:
        - socks5h://tegress.homelab.internal:9050
