---
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: nfs.csi.k8s.io
  name: automation-platform-storage
  namespace: automation
spec:
  capacity:
    storage: 20Gi
  accessModes:
  - ReadWriteMany
  storageClassName: nfs-csi
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
  - nolock
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: /
    volumeAttributes:
      server: unas.internal
      share: /var/nfs/shared/automation_platform_data
    readOnly: false
