---
helmfiles:
  - path: ../../helmfile.d/01-bootstrap.gotmpl.yaml
    values:
      - cluster: mlops
      - identityOverlay: ../clusters/mlops/identity-values.yaml.gotmpl
      - meshOverlay: ../clusters/mlops/clustermesh-values.yaml.gotmpl
