---
clusterName: &cluster homelab-mlops
# renovate: datasource=docker depName=ghcr.io/siderolabs/installer
talosVersion: v1.9.1
# renovate: datasource=docker depName=ghcr.io/siderolabs/kubelet
kubernetesVersion: v1.32.0
endpoint: https://${HOMELAB_MLOPS_MASTER01_DNS}:6443
additionalApiServerCertSans: &san
  - ${HOMELAB_MLOPS_MASTER01_IP}
  - ${HOMELAB_MLOPS_MASTER01_DNS}
  - 127.0.0.1
additionalMachineCertSans: *san
allowSchedulingOnMasters: true
cniConfig:
  name: none

nodes:
  - hostname: mlops-master01.local
    ipAddress: ${HOMELAB_MLOPS_MASTER01_IP}
    installDisk: /dev/vda
    controlPlane: true
    disableSearchDomain: true
    networkInterfaces:
      - interface: eth0
        dhcp: true
    # nodeLabels:
    #   topology.kubernetes.io/region: mlops
    #   topology.kubernetes.io/zone: cp
    schematic:
      customization:
        systemExtensions:
          officialExtensions:
            - siderolabs/intel-ucode
            - siderolabs/qemu-guest-agent

  - hostname: mlops-worker01.local
    ipAddress: ${HOMELAB_MLOPS_WORKER01_IP}
    installDisk: /dev/vda
    controlPlane: false
    disableSearchDomain: true
    networkInterfaces:
      - interface: eth0
        dhcp: true
    # nodeLabels:
    #   topology.kubernetes.io/region: mlops
    #   topology.kubernetes.io/zone: wk
    schematic:
      customization:
        systemExtensions:
          officialExtensions:
            - siderolabs/intel-ucode
            - siderolabs/qemu-guest-agent
            # - siderolabs/intel-ice-firmware

  - hostname: mlops-worker02.local
    ipAddress: ${HOMELAB_MLOPS_WORKER02_IP}
    installDisk: /dev/vda
    controlPlane: false
    disableSearchDomain: true
    networkInterfaces:
      - interface: eth0
        dhcp: true
    # nodeLabels:
    #   topology.kubernetes.io/region: mlops
    #   topology.kubernetes.io/zone: wk
    schematic:
      customization:
        systemExtensions:
          officialExtensions:
            - siderolabs/intel-ucode
            - siderolabs/qemu-guest-agent
            - siderolabs/intel-ice-firmware

patches:
  - "@./patches/cluster-discovery.yaml"
  - "@./patches/disable-search-domain.yaml"
  - "@./patches/kubelet.yaml"
  - "@./patches/host-dns.yaml"

controlPlane:
  # nodeLabels:
  #   topology.kubernetes.io/region: *cluster
  #   topology.kubernetes.io/zone: cp
  patches:
    - "@./patches/master/api-access.yaml"
    - "@./patches/master/controller.yaml"
    - "@./patches/master/cluster-config.yaml"
    - "@./patches/master/etcd.yaml"

worker:
  # nodeLabels:
  #   topology.kubernetes.io/region: *cluster
  #   topology.kubernetes.io/zone: wk
  patches:
    - "@./patches/worker/gpu-worker-patch.yaml"
