---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: security
resources:
  # https://external-secrets.io/latest/examples/bitwarden/#deploy-bitwarden-credentials
  - secret.yaml
  - deployment.yaml
  - service.yaml
