---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: comfyui
  namespace: ai
  labels:
    app: comfyui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: comfyui
  template:
    metadata:
      labels:
        app: comfyui
    spec:
      runtimeClassName: nvidia
      nodeSelector:
        kubernetes.io/hostname: mlops-work-00
        nvidia.com/gpu.present: "true"
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: comfyui
          image: ghcr.io/nextgensolutions-llc/comfyui:test
          imagePullPolicy: Always
          args: ["--listen", "0.0.0.0"]
          ports:
            - containerPort: 8188
              name: http
          resources:
            limits:
              nvidia.com/gpu: 1
          volumeMounts:
            - name: model-folder
              mountPath: /usr/local/ComfyUI/models
      volumes:
        - name: model-folder
          hostPath:
            path: /usr/local/ai/models/comfyui
            type: DirectoryOrCreate
