apiVersion: ENC[AES256_GCM,data:psg=,iv:jKpci9cBWC/sUfxe8/uEgGEKfvxJ9On9UAEu4QczYLY=,tag:f03nJ1TgkF9/JTRSV0WDlQ==,type:str]
kind: ENC[AES256_GCM,data:M8DsMXKY,iv:s//To79cy+GewhVcveU/736EKyhjN8iggbXJNc6jDMU=,tag:2UrJuRv9/MZrUNfHZ0NzqQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:I/0Qev0GupChb+4pft+Ou7Y=,iv:iE3ASX5SoACkETmWbsY/bcTTtXqC5tqeNlcjffk2QKg=,tag:HAxmjShXZL+tUyAzA/5CnQ==,type:str]
    namespace: ENC[AES256_GCM,data:Yj0=,iv:J9a67MmZ6tZxPRdxD5QOaVpuvuWxCb6hZOyp/mNvNf8=,tag:ok1aym8vCSIT3VVboBq0NA==,type:str]
type: ENC[AES256_GCM,data:T7oJ+nRM,iv:u5T+X/8dN50vmN94ilCw3k56B5fMBkPwTtqDIIu1aQo=,tag:oV5G49SRzZcNHhxrPtp0HA==,type:str]
stringData:
    Authorization: ENC[AES256_GCM,data:B9rYXkcydGAufZ03o76I4RdMMzvzQJTB/ofBJr4BCFn0dd1T+TbjDDSDgqvlkPY2mQSBUKu90lpTxzmOwas7gUrRbU9ZNDydJIzsID89b/x1SVPbxxdNNnPqyJizqOTKcmHQBpn4A+xUZ+vU,iv:PL7BbQnb6DBexr9+byKZYiogeTE0tiFAFWV6mWa7mI8=,tag:zE+Kg8TYsmPN1wmeeUPS/A==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:626956831217:key/f22ea8b8-ec28-4d80-988e-7372419dbc28
          created_at: "2026-07-02T16:48:38Z"
          enc: AQICAHgf2Bz/yC/N+d80dqtXyzpCypiaZx1Lgwl8YcJR1TYnOAFTxf0UIKegmVLSvHFkjZp8AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMUOYtvKzwySY8Mm1UAgEQgDvVBeedeNe2RFDCr613CoqxXnXPxi7zagJkq7yksVK5bTEhBowLvGmhFtse4eUC6KIi5uEl927f6RoRag==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-07-02T16:48:38Z"
    mac: ENC[AES256_GCM,data:RcusFoWkOX5IaUHdg5GMo1XcnJWPCrwv39oNPvE3gmWAXCXPB0K/euZM3kRK6dPxSyBGqWBdK2QAmMDneCfx1eqoM9LWQ1uVfhsxOvv94epuiNkd1MVYiGjz5ltwZLeyZNa1kU6hw1ZM87O5gVM7S5attvUkUA5yT1BNVRKYoaE=,iv:DtsFIOac56BMgiSy5h4E8RKxj+0s8RalG+MTjZkMa/k=,tag:hxQVk6rpeM2x8Iprk3H7cA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|apiVersion|metadata|kind|type)$
    version: 3.8.1
