---
version: 3

includes:
  ai:
    taskfile: ai/Taskfile.yml
  automation:
    taskfile: automation/Taskfile.yml
  observability:
    taskfile: observability/Taskfile.yml

tasks:
  deploy:
    dir: platform
    summary: 'deploy all platform services running on kubernetes'
    cmds:
      - task: ai:deploy
      - task: automation:deploy
      - task: observability:deploy

  destroy:
    dir: platform
    summary: 'destroy all platform services running on kubernetes'
    cmds:
      - task: ai:destroy
      - task: automation:destroy
      - task: observability:destroy
