---
version: 3

includes:
  data:
    taskfile: data/Taskfile.yml
  ai:
    taskfile: ai/Taskfile.yml
  automation:
    taskfile: automation/Taskfile.yml
  observability:
    taskfile: observability/Taskfile.yml

tasks:
  deploy:
    dir: platform
    summary: 'deploy all platform services running on kubernetes'
    cmds:
      - task: data:deploy
      - task: ai:deploy
      - task: automation:deploy
      - task: observability:deploy
      - kubectl rollout restart deployment reflector -n kube-system

  destroy:
    dir: platform
    summary: 'destroy all platform services running on kubernetes'
    cmds:
      - task: ai:destroy
      - task: automation:destroy

  test:
    dir: platform
    cmds:
      - task: ai:test
