---
version: 3

includes:
  ai:
    taskfile: ai/Taskfile.yml
  automation:
    taskfile: automation/Taskfile.yml

tasks:
  deploy-platform:
    dir: platform
    cmds:
      - ai:deploy
      - automation:deploy
