---
version: 3

includes:
  data:
    taskfile: data/Taskfile.yml
  ai:
    taskfile: ai/Taskfile.yml
  automation:
    taskfile: automation/Taskfile.yml
  downloads:
    taskfile: downloads/Taskfile.yml
  media:
    taskfile: media/Taskfile.yml
  observability:
    taskfile: observability/Taskfile.yml

tasks:
  deploy:
    dir: platform
    summary: 'deploy all platform services running on kubernetes'
    requires:
      vars: [CLUSTER]
    vars:
      KUBECONFIG_FILE: '{{.ROOT_DIR}}/kubernetes/generated/{{.CLUSTER}}/kubeconfig'
    cmds:
      - task: data:deploy
        vars: { CLUSTER: '{{.CLUSTER}}' }
      - task: ai:deploy
        vars: { CLUSTER: '{{.CLUSTER}}' }
      - task: automation:deploy
        vars: { CLUSTER: '{{.CLUSTER}}' }
      - task: observability:deploy
        vars: { CLUSTER: '{{.CLUSTER}}' }
      # - kubectl rollout restart deployment reflector -n kube-system

  destroy:
    dir: platform
    summary: 'destroy all platform services running on kubernetes'
    cmds:
      - task: ai:destroy
      - task: automation:destroy

  test:
    dir: platform
    cmds:
      - task: ai:test
