---
apiVersion: agentgateway.dev/v1alpha1
kind: AgentgatewayParameters
metadata:
  name: agentgateway-otel
  namespace: ai
spec:
  env:
    - name: OTEL_EXPORTER_OTLP_ENDPOINT
      value: "http://otel-collector-collector.monitoring.svc.cluster.local:4317"
    - name: OTEL_EXPORTER_OTLP_PROTOCOL
      value: "grpc"
    - name: OTEL_SERVICE_NAME
      value: "agentgateway"
    - name: OTEL_TRACES_EXPORTER
      value: "otlp"
    - name: OTEL_LOGS_EXPORTER
      value: "otlp"
  rawConfig:
    config:
      tracing:
        otlpEndpoint: "http://otel-collector-collector.monitoring.svc.cluster.local:4317"
        otlpProtocol: grpc
