---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
helmCharts:
  - name: calibre
    releaseName: calibre
    chart: k8s-home-lab/calibre-web
    version: 9.0.2
    values:
      - values.yaml
    secrets:
      - secrets.yaml
  