---
apiVersion: aigateway.envoyproxy.io/v1alpha1
kind: AIServiceBackend
metadata:
  name: ollama-backend-service
  namespace: ai
spec:
  schema:
    name: OpenAI
  backendRef:
    name: ollama
    kind: Service
    port: 11434
