---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: feeds
resources:
  - deployment.yaml
  - service.yaml
  - pvc.yaml
configMapGenerator:
  - name: freshrss-scripts
    files:
      - scripts/provision.sh
  - name: freshrss-opml
    files:
      - opml/homelab.opml
      - opml/youtube-subscriptions.opml
