---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: feeds
resources:
  - deployment.yaml
  - service.yaml
  - pvc.yaml
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: freshrss-scripts
    files:
      - scripts/provision.sh
  - name: freshrss-opml
    files:
      - opml/homelab.opml
      - opml/youtube-subscriptions.opml
      - opml/.checksum
replacements:
  - source:
      kind: ConfigMap
      name: freshrss-opml
      fieldPath: data.[.checksum]
    targets:
      - select:
          kind: Deployment
          name: freshrss
        fieldPaths:
          - spec.template.metadata.annotations.[checksum.opml]
        options:
          create: true
