---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: freshrss-data
  namespace: feeds
spec:
  storageClassName: nfs-csi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
