apiVersion: ENC[AES256_GCM,data:WQk=,iv:jFCc6ko511ce06Y5YVxAPW+VkQZA1HPMGk+Cc5wq104=,tag:Q0PoCYTkf92LpLYiCDCCmQ==,type:str]
kind: ENC[AES256_GCM,data:mD5lT824,iv:kkwTbdzP8La5T2JZPrQ+wDCOBApFnLw4uPfjIPTAyd0=,tag:CLgkFxpC3J/kYBHbiCqpog==,type:str]
metadata:
    name: ENC[AES256_GCM,data:7wmL3W2md2gQUjFoU14=,iv:mJZCajw+iO7lAPlJ9dRjgUY2+N+8kLV1SRkiSF0ktFE=,tag:gbiaXT/TEhkUEliwfjy34w==,type:str]
    namespace: ENC[AES256_GCM,data:5nEv8oI=,iv:XOOJ9diAUFI/xJO0yDTu2iW9iEk0RkPoVOD/afAt8gc=,tag:XEtSSz2AYPfcusETylWoEw==,type:str]
type: ENC[AES256_GCM,data:oDYNCd7U,iv:BaGKWUzihNhIotdRBAfg3miDaJdUO1Q6OwHFjt9DErQ=,tag:+I6SJt8Zqo61TDwYVXSEqQ==,type:str]
stringData:
    admin-password: ENC[AES256_GCM,data:43X0gNDw89uDmteSyxQopmE0sowg7Ii2o9LdgYRgh6P3FnujH3YYP1LBxNILTr4p,iv:podVRVcVV9NUe0/ojLyPDMAmU7ye7E0GRGfxI+B2nKc=,tag:UDnpIokXOhQXtfzaU5NCHw==,type:str]
    admin-api-password: ENC[AES256_GCM,data:a4UWHb1zD9c6+EXpPCWrg2amB6DejAf1Rj3H98BFxTXdirkHCoz64yXF9EIkVGQZxIXrm/1eZnxLr/kaigpkAA==,iv:RNl5rde9pI+mWxZMRYVdA1053Dx2C6hEk9zVyTiswGI=,tag:83jBviiQWk8WZLImGPCVCQ==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:626956831217:key/f22ea8b8-ec28-4d80-988e-7372419dbc28
          created_at: "2026-06-26T22:20:32Z"
          enc: AQICAHgf2Bz/yC/N+d80dqtXyzpCypiaZx1Lgwl8YcJR1TYnOAFN6Gl4Qnz8HkyzzEPA/8dWAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMEeDxlXOlAgErczydAgEQgDuOcsW0jv4xn8xTDMGxsq7X9U+VmcyWc2LRJrB3axa49yj+YP5Qy2PGwsWs506gxZ3VORpcRG5K994YOw==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-06-26T22:20:33Z"
    mac: ENC[AES256_GCM,data:wl/c4oWShYakyuLWUMCNMqFjFslvufaKyZPTDHagAYr4IcctRBrPzjiaBMfIg1+yAbdwdJhFeqluvJ2RUToTPYQDTcuEB4hT/PYYfouIpb79ZtBUNcVAkJszG+OathK8NUCxVX8xvXep0CbtWpPIoxkQ/YypsD5Ov2zSlFXZhBg=,iv:txbk8TkoIJqF8VivHc1TQxv0dvfbtSlNtpusfE/JFME=,tag:Zt6t4a65GGhQMvAkNvzOQA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|apiVersion|metadata|kind|type)$
    version: 3.8.1
