---
apiVersion: kagent.dev/v1alpha2
kind: ModelConfig
metadata:
  name: claude-opus-4-5
  namespace: ai
spec:
  provider: Anthropic
  model: anthropic-claude-opus-4-5-latest
  apiKeySecret: anthropic-api-key
  apiKeySecretKey: Authorization
