---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: influxdb
  namespace: observability
spec:
  instanceSelector:
    matchLabels:
      dashboards: grafana
  datasource:
    name: InfluxDB
    uid: influxdb
    type: influxdb
    access: proxy
    url: http://influxdb.homelab.internal:8086
    jsonData:
      version: Flux
      organization: homelab
      defaultBucket: hardware
      httpMode: POST
      tlsSkipVerify: true
    secureJsonData:
      token: ${INFLUXDB_ADMIN_TOKEN}
    isDefault: false
    editable: true
