---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: homelab-cert
  namespace: networking
spec:
  secretName: homelab-tls
  dnsNames:
    - homelab.local
    - "*.homelab.local"
  issuerRef:
    name: internal-ca-cluster-issuer
    kind: ClusterIssuer