apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ai
helmCharts:
  - name: substrate-crds
    repo: oci://ghcr.io/kagent-dev/substrate/helm/substrate-crds
    version: 0.0.7
    releaseName: substrate-crds
    namespace: ai
    includeCRDs: true
