---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: comfyui-ingress
  namespace: ai
spec:
  rules:
  - host: "comfyui.homelab.internal"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: comfyui
            port:
              number: 8080
