apiVersion: ENC[AES256_GCM,data:i1c=,iv:TVuKwTOy9tm/fBKFmQ+Crp4wIc8UJpA/v5VMGU0FRlk=,tag:cUiO22rgYZ1gtSQbKr4z5A==,type:str]
kind: ENC[AES256_GCM,data:ofMRqoHO,iv:K3r+csTmw8TEgEEy1iGXpMT2yQQPab6WiwSTiS4/bZw=,tag:u++fjUc4Gs/vMaMfKl8gew==,type:str]
metadata:
    name: ENC[AES256_GCM,data:I912YtMCcA9Q24epir+w,iv:laYOc2MUf6I1v35HYseISEh4fMxDnLFtRmCYj8QwFmI=,tag:txF6q1D9tKBhlf0x1N7fgA==,type:str]
    namespace: ENC[AES256_GCM,data:kgU=,iv:3Jl1N0IcD2eiU0Ud1LRQR+pHjI7h3nBD34e9JRuESgo=,tag:vO8YpY0IJ+1QPiIri3OIpw==,type:str]
type: ENC[AES256_GCM,data:DsHgaO4f,iv:t1bIVWvJQetQi3uzjhcFmiJeYM10JHo5Iw7AU+7p90o=,tag:5yaf6vNmvzQZO6JRGi0cuA==,type:str]
stringData:
    SEARXNG_SECRET: ENC[AES256_GCM,data:8vImKhWKV5zi5jZyCZCM/AcJDTflX3SJzrauAkz/Pz5UdtfRx+3/9r2ub370ogJ8gwjRl5FXrgijIG4dKfRCxg==,iv:cQO0cxdjL1BnSTtNwW4MQvBosusfB9DCB6UkcfJJ8YU=,tag:PWMEZky5TJM4xOa4RLU70g==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:626956831217:key/f22ea8b8-ec28-4d80-988e-7372419dbc28
          created_at: "2026-09-18T16:24:06Z"
          enc: AQICAHgf2Bz/yC/N+d80dqtXyzpCypiaZx1Lgwl8YcJR1TYnOAE1oyp3KITh/du5cW6ELGLtAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQML+Lu54VUOPlewVooAgEQgDvMZs/eZ+Mp+5THADY9PmazBffWc5aL1TvcTiADMK+Xn4ChRqADkH4e56w8BdE+Mrb+M2bFQiULvfZBRg==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-09-18T16:24:06Z"
    mac: ENC[AES256_GCM,data:sDaGsdknixKtctEnlBZ0sow/om05lSMJU3af3K5ICwIL7ahLu9nY+Wm0ds8DVMcZVv1k3QcoscX+X2x6mkVFLrP2ydRjhXKHuhA/1KzjUQUWpa7z+hFWN/tsQ6az4ltgTLp/ONfU6LsPfSqusnhFKqYrwsmzKoa2Mmy1hPcf6fw=,iv:/EilgIt8fwJjOx3nOlGORET2CFXQAOxKn27i9tvzLWU=,tag:OOK4BAWN725KsgdKuyrtJg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|apiVersion|metadata|kind|type)$
    version: 3.8.1
