# ---
# bases:
#   - ../defaults.yaml

# repositories:
#   - name: argo-cd
#     url: https://argoproj.github.io/argo-helm

# releases:
#   - name: argo-cd
#     namespace: argocd
#     chart: argo-cd/argo-cd
#     version: 7.7.16
#     createNamespace: true
#     values:
#       - ../apps/gitops/argocd/values.yaml.gotmpl
#     hooks:
#       - events: ["postsync"]
#         showlogs: true
#         command: "bash"
#         args:
#           - -c
#           - |
#             kustomize build --enable-exec ../apps/gitops/argocd | kubectl apply -f -