version: 3

includes:
  talos:
    taskfile: ".taskfiles/talos/Taskfile.yaml"

tasks:
  provision-mlops-cluster:
    dir: kubernetes
    cmds:
      - |
        if [ -f ../.envrc ]; then
          source ../.envrc
        fi
      - make tf_run

  bootstrap-mlops-cluster:
    dir: kubernetes
    cmds:
      - make helmfile_lock
      - make helmfile_apply

  destroy-mlops-cluster:
    dir: kubernetes
    cmds:
      - make tf_destroy
