version: 3

includes:
  talos:
    taskfile: ".taskfiles/talos/Taskfile.yaml"

tasks:
  provision-cluster:
    dir: kubernetes
    cmds:
      - |
        if [ -f ../.envrc ]; then
          source ../.envrc
        fi
      - make tf_run

  bootstrap-cluster:
    dir: kubernetes
    cmds:
      - make helmfile_lock
      - make helmfile_apply

  sync-cluster:
    dir: kubernetes
    cmds:
      - make helmfile_sync

  destroy-cluster:
    dir: kubernetes
    cmds:
      - make tf_destroy

  reboot-cluster:
    dir: kubernetes
    cmds:
      - task: talos:reboot-node