version: 3

includes:
  talos:
    taskfile: ".taskfiles/talos/Taskfile.yaml"

tasks:
  generate_tf_variables:
    dir: kubernetes
    cmds:
      - |
        echo "Generating terraform.tfvars from .env file..."
        if [ -f .env ]; then
          awk -F= '/^[^#]+/ {print $1 " = " $2}' .env > terraform/terraform.tfvars
        else
          echo "No .env file found. Skipping terraform.tfvars generation."
        fi
    silent: true
    sources:
      - .env

  provision-mlops-cluster:
    dir: kubernetes
    cmds:
      - |
        if [ -f ../.envrc ]; then
          source ../.envrc
        fi
      - task: generate_tf_variables
      - make tf_run

  bootstrap-mlops-cluster:
    dir: kubernetes
    cmds:
      - make helmfile_apply

  destroy-mlops-cluster:
    dir: kubernetes
    cmds:
      - make tf_destroy
