---
version: 3

includes:
  talos:
    taskfile: ".taskfiles/talos/Taskfile.yaml"

vars:
  TERRAFORM: tofu -chdir=terraform

env:
  PROXMOX_VE_USERNAME: "{{.PROXMOX_USERNAME}}"
  PROXMOX_VE_PASSWORD: "{{.PROXMOX_PASSWORD}}"
  PROXMOX_VE_ENDPOINT: "https://{{.PROXMOX_NODE_TWO_IP}}:8006"
  PROXMOX_VE_API_TOKEN: "{{.PROXMOX_NODE_TWO_API_TOKEN}}"
  PROXMOX_VE_SSH_AGENT: "false"
  PROXMOX_VE_SSH_PRIVATE_KEY: "{{.PROXMOX_NODE_TWO_PRIVATE_KEY}}"

tasks:
  provision-cluster:
    dir: kubernetes
    cmds:
      - |-
        {{.TERRAFORM}} init --upgrade
      - |-
        {{.TERRAFORM}} plan \
          -var control_plane_ip=${MLOPS_CONTROL_PLANE_IP} \
          -var network_gateway=${PROXMOX_NETWORK_GATEWAY} \
          -var proxmox_ssh_private_key=$PROXMOX_NODE_TWO_PRIVATE_KEY
      - |-
        {{.TERRAFORM}} apply -auto-approve \
          -var control_plane_ip=${MLOPS_CONTROL_PLANE_IP} \
          -var network_gateway=${PROXMOX_NETWORK_GATEWAY} \
          -var proxmox_ssh_private_key=${PROXMOX_VE_SSH_PRIVATE_KEY}

  destroy-cluster:
    dir: kubernetes
    cmds:
      - |-
        {{.TERRAFORM}} init --upgrade
      - |-
        {{.TERRAFORM}} destroy -auto-approve \
          -var control_plane_ip=${MLOPS_CONTROL_PLANE_IP} \
          -var network_gateway=${PROXMOX_NETWORK_GATEWAY} \
          -var proxmox_ssh_private_key=${PROXMOX_VE_SSH_PRIVATE_KEY}

  bootstrap-cluster:
    dir: kubernetes
    cmds:
      - make helmfile_lock
      - make helmfile_apply

  sync-cluster:
    dir: kubernetes
    cmds:
      - make helmfile_sync

  test-cluster:
    dir: kubernetes
    cmds:
      - echo "executing tests"

  reboot-cluster-node:
    dir: kubernetes
    cmds:
      - task: talos:reboot-node

  cluster-health:
    dir: kubernetes
    cmds:
      - |
        until kubectl get nodes --no-headers | awk '{print $2}' | grep -q "NotReady"; do
          echo "Waiting for Kubernetes cluster to become healthy..."
          sleep 10
        done
        echo "Kubernetes cluster is healthy!"
