---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: automation
resources:
  - deployment.yaml
  - service.yaml
  - configmap.yaml
  - pvc.yaml
  - workflows-pvc.yaml
  - workflows.yaml
  - credentials.yaml

generatorOptions:
  disableNameSuffixHash: true