apiVersion: ENC[AES256_GCM,data:d/o=,iv:eg11fqs//8PQQM5CNsX6g/FP2GEvQfRK0zAdaW7uppE=,tag:M6/06RXsnC45cL0MyjO0Yg==,type:str]
kind: ENC[AES256_GCM,data:uLpwp3+H,iv:mPBs//YSDh9xY9jDlU/rnmEmgcZj5IFiZ2sm/3IX5K8=,tag:LoConNWM8wmNNVa9xmXiMw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:ugQZikmlj86BlzvzcuAowpQ=,iv:HqHk8HFz6rkAPjXh0x3w5JGXvW4RHA9azEoFVUcHqKA=,tag:Ctz94Ke5eTV2KPrNf5+1fg==,type:str]
    namespace: ENC[AES256_GCM,data:goY=,iv:qprp1kraAFcb4I9cT6xwYNUVgJ7RjK4gxtBxG7DwkWY=,tag:ar/AImD+MrDgVBkSlWf0Vg==,type:str]
stringData:
    github_token: ENC[AES256_GCM,data:a4KAvDswtTwf22CcGvppAKZT6ximDGRCSxdzGr1UjvfF4iJR9OQzZA==,iv:SoZqatDa2om+tlBAvrdbla0HmTukJQ8ZSX4FR5RVaAw=,tag:z6+NbLJLEVPyyb4vxV3uWQ==,type:str]
    n8n_api_key: ENC[AES256_GCM,data:ttLa9p3dUZLLIhsJK06xPAs9E5G1ovpm9Y4wjypGt1SPBJoIjhiVSAlm41XSruhu2+eh5BL2v6gXFI3ftbTN827ATS81xPoJd4CwG1mRVCB77Aoqr0yF7OT3WKBkxgcsuyPDOOe9BhNVfyQOPtEiLfCRegzvh1cUTBpj13redBj/OnzpDMzItyC0kdlEbzNwXqqUoXILvkBgK8N1Dse6BWCML+8JHZNQwYYHhxizL63U/xBEUJPzbGpOHTbOxR178Sn6fZ1ujNq6DxBXKNYo,iv:hIvrwYJ5l43IYh3os2NRaBtfHlGcxmS36TWkTXNnCgE=,tag:diVxjmMZef05NkYWLPyFQg==,type:str]
    webui_api_key: ENC[AES256_GCM,data:ZvMVGVBGNJwR4H8GyWcRSLp0Rz91LMOWHi4=,iv:WKLu8Ea1E6PBAUXE6e3C4NK9RDBM64ac7swxBpviv38=,tag:feZiE/q5nA9yd+W//eEfow==,type:str]
    webui_secret: ENC[AES256_GCM,data:g49jk4KXlC87rhJnoH/xoq6r+0c4tQuBIkTZrPOODO3a83dwjw==,iv:oUMs3G1W8KqayZJgsj5OQfAYrdxyHRQ59EZm1EPs8bc=,tag:kCsSDZYwibMjbgX2CUjrnQ==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:626956831217:key/f22ea8b8-ec28-4d80-988e-7372419dbc28
          created_at: "2026-06-17T19:31:06Z"
          enc: AQICAHgf2Bz/yC/N+d80dqtXyzpCypiaZx1Lgwl8YcJR1TYnOAF0sHKhnyOCtCeFdCHTFobVAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMJHw56Yb2AtGwg6flAgEQgDvtkKxc/0bPXWKDmVUIKSGliUdhXFvacVqWL/XLt85I+CzX+NTSPYFw+KnF92ygTNvtvRcxIy7EarzWaA==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-06-17T19:31:06Z"
    mac: ENC[AES256_GCM,data:zUAfriNWmCfsyERlWkFAlOMxstOaUd8NRT0BwHLbOFpeNINR2C1mvOx/3FNFVWQwAF+XmwVIqRtCFIYMMuo+L6SLZrhzMzCAfWBIt6Nx5euv5Cw7u93ubPfoEx3Ki6UnWsXEeFe7Vt0gB5LTqw9vzGDww5s4jyqP8EnzBjkxsdo=,iv:OxrUWmMCFvTuVfxVkSpqkUPLxLsAUxr5ns5G0POzcsU=,tag:R62UgxY24DXhnkWKV5g47g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|apiVersion|metadata|kind|type)$
    version: 3.8.1
