apiVersion: ENC[AES256_GCM,data:OnY=,iv:wvLte7WeARlKuieywv5GnPH7pX7EknuPCnH808u7TXI=,tag:rX1MwdTKA0AEpAyf0kbyew==,type:str]
kind: ENC[AES256_GCM,data:uo4WyULK,iv:5XnyLGF8/sjxlpSJB9ZFLu9bP3XFmYbUg2ClT6ulZ1Q=,tag:tIbXAp2ITRuqYUS71p06Uw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:cB1I9RDbb8j84e7cn+4mPXg=,iv:r8KJSbSeAqby6Cj9t3h4A6cV3fZxa9NtZLADRQ9blK8=,tag:DoJHlGs53p2pux/CiXG7Zg==,type:str]
    namespace: ENC[AES256_GCM,data:C0A=,iv:FgzFelstPkV/tCvBRTKndHiE2n/I3DwQk8zTtmg61Z8=,tag:N6jtXm3UBlbZhwGKXmBEZA==,type:str]
stringData:
    github_token: ENC[AES256_GCM,data:DDg2++aCpeDonM15lMABF3K+tg+cDa3iC/B4d4+IF1GRo8hOq2zLEA==,iv:GAnN0K8srArDpOM2VkMaGfLlGTGywNs0xCxJSeI1Y1U=,tag:Lncpd41rGxXhv0fw3bftdw==,type:str]
    n8n_api_key: ENC[AES256_GCM,data:eMxm72BTLexKuYvYydfhJlzRc+FVlH3CO2pbTUGtxxJWJALfo2RUT+cr60rBrOl9GbelnSDSITcOfkSUNuaEHgMATGRRfhiJwq/o07VJ0bfBf+8h4uoypm0zHZGEzT5Se0dcxGHyg0trT64BAZ9v/Z+ZEoG2piIcO1pKuIySJYsr+5PzTOhDmDf81+z6f2E7GXOYFQ/u8JnTt0o0MwbLZP0WjlCyCL4XVPheobI/MW03GVS83W9hziKLEDCl1uXYJOcGZNumbSBy7x0cUIf1,iv:YDgGpeioU+riap8vhq5F1wWKk0RrSevDoeDd/VW8pm4=,tag:k7aReYgn0yokBCY/kITZ1Q==,type:str]
    webui_api_key: ENC[AES256_GCM,data:LTTCpY0obwqShsjbkkB7Rbx0oJWWRvvEt9Y=,iv:zdqKh9kGXVTXK/p88F4TJXNMxGEmR+HCe0FOTmbi1+w=,tag:wemDNFeUCDhiJHgxuv1IWA==,type:str]
    webui_secret: ENC[AES256_GCM,data:tuQDjSPtmI9zRnubVwGGb2oFEEcq1YqwMzWApOEhVUjXz3UA8A==,iv:qBsljMt81kXwrOCGZHKAO2i+ZkAxR3IAho4LnJK8fV4=,tag:lz4aswH+5+mVGweoiW28Pg==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:626956831217:key/f22ea8b8-ec28-4d80-988e-7372419dbc28
          created_at: "2026-05-21T21:33:15Z"
          enc: AQICAHgf2Bz/yC/N+d80dqtXyzpCypiaZx1Lgwl8YcJR1TYnOAEYPszA2GCihEwuc345d/DXAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMJX+JJ401PoIO+S5hAgEQgDuvlYCHhwZREvuHsIFeaqhBJ8jGSAy0lfglJ6gx+AMGy1LJUkc6fUQOEQz4UCYZQ2nL+hNAJLE2wlzc8Q==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-05-21T21:33:16Z"
    mac: ENC[AES256_GCM,data:gTxKtc3nN9aJrWAdpK41tS35Tnfh0fcgB6uQi9hHxMWatbH8rc6qPJQqaC9B03k0ATWUHDdyWc4SpBbW7t71aNHz6/LNWWApilS4v0l6AbsSYuRWpgHHmb+3FQGSKUR6/e8pzY5lfeBMhe6Sb+8y0GBNj1U+a/+lfeUr3dzHDWU=,iv:gZlzN9P5sR3OT1fuDYQLtdvIkxsmzucYHrKu6vKTtog=,tag:WL0Cr1IuJLDYekzR20Ht8g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|apiVersion|metadata|kind|type)$
    version: 3.8.1
