apiVersion: ENC[AES256_GCM,data:x/4=,iv:hikrxkEZHdxNGLXU14zypc4MYvaxpmXwB7haxSFIZto=,tag:gFad1Vp6cHq2EE0vmRcXzw==,type:str]
kind: ENC[AES256_GCM,data:CYjNSnFr,iv:79fpHgXAtDMVKsxlYaqteZDVKMQ1wkvTIlPuJbOPruY=,tag:fw+ctit4bg61YF9KTT1Fgg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:BsU30Wl1AgqK7iw6pUB2oGM=,iv:9seecWMfWxb61U6kqaE4IrytywsrYWmidpEOR7g/mCM=,tag:N/dn2jc4EJbwG4im+ae2OQ==,type:str]
    namespace: ENC[AES256_GCM,data:Zqs=,iv:4sHLUW3diAKcQ+ojhQ3JBQzY8Yjd5DmqUmO0pcfZ0eQ=,tag:NuiRB/d2PsmWwfqIH/5ecw==,type:str]
stringData:
    github_token: ENC[AES256_GCM,data:P7j4IezKyYn/E0svmzqq4VylYS1IsydJCroKdRwU0K7puaF8agEwcw==,iv:dMkr9EOwnIDVln1T3JOocqZ99FiHUofN3a4vXOmEb1U=,tag:fzq+keiyK1yE6dhama6KvQ==,type:str]
    n8n_api_key: ENC[AES256_GCM,data:01zqyk4luQ8fYw/BJZHWq+UPMkoy17TVTtvdw563UEan5SariyvIn/bcHjMVgGDH4zyI80tkCWrRQFGC/Nf1oT2KWZtcjkXVQH9xgOYJ89PQ3rapFouLb9iW+xXhoarSjlBiY5sAWCqnSYte/ODe8QdURLPUSuss5pR2q0TsLLQVPKU2J+NrY1ON65M+aMMFKlI7URsgG0+dCknjyRdtiwwuJziaYrO8f3xnRQ8+0Ta1bazGKm+AREm4LtyHm+fAK3g7JxOdp9NXcG/+zChz,iv:Ym1ZKkvhZiudHMhzRYzuXZkRD2mIs3ye2aic5HC9PL8=,tag:NolO9OytJqwwX4N6gPgszQ==,type:str]
    webui_api_key: ENC[AES256_GCM,data:C8L5AUocHE7pzxWJDpDHT9viq7EP98kOl54=,iv:k4LYvqF6DeOjvOxL3120vgm3PkXwGWJFEQPIAVbTvs8=,tag:7sQIxk6bXe+aNxUuTGonZA==,type:str]
    webui_secret: ENC[AES256_GCM,data:Crg9EBGHi37dYA3bKaDFJfFbJtBo0WklhgJtDzjnx1ir8mh1aQ==,iv:tsHexGQoEsZATZdsuquTffbwANfTQ5e1Ia+fFzoVhLw=,tag:m1wf1lL5CIRtMC5V+IC0rw==,type:str]
    qdrant_api_key: ENC[AES256_GCM,data:v7+hkETzIP4W2ryFxTH+wB9TLZG6p2czUw==,iv:h0en9DbCwv/DJee1EbfbIDheUHbeL3ZltC38UHcpa/4=,tag:ROtFC72HM8VJkW15dxVtjg==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:626956831217:key/f22ea8b8-ec28-4d80-988e-7372419dbc28
          created_at: "2026-10-03T20:29:22Z"
          enc: AQICAHgf2Bz/yC/N+d80dqtXyzpCypiaZx1Lgwl8YcJR1TYnOAEEBd5u4fDis8xCyakD3y75AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMZKQJVD6poMmf/cDhAgEQgDuBIKO+rZgn1U1uN7D1OgBhqTJt3IuTWrM5o66UU87qIvLu8as5ugeKY8y+YjWlPnCCiGOf14jW/vgIsg==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-10-03T20:29:22Z"
    mac: ENC[AES256_GCM,data:i0aWhqGd7UJELT3GbWHL6T3VbA172MwiU1dY/GZsPWJAh0VKMp5aOel9mbvAGABQ0KUz7cAKO/XfRMgAKFgA6uSY+JjyEazsHjOyHup+fy8SewZTdUNIVTxpKxZBFbWVOqojJQIZGHrC3APtrE6o2Ik4+YulNrvPf5oAhvL5gCM=,iv:B5+TcwOlyitJWXSrmuMAXb+yi7b9o+8l7PdFQJ/1fRI=,tag:dzrGAv4Zq/OJeVsPgp21zw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|apiVersion|metadata|kind|type)$
    version: 3.8.1
