services:
  netbootxyz:
    image: netbootxyz/netbootxyz
    container_name: netbootxyz
    ports:
      - 3000:3000
      - 69:69/udp
      - 8080:80
    volumes:
      - /opt/netboot/config:/config
      - /opt/netboot/assets:/assets
    restart: unless-stopped
