---
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: nfs.csi.k8s.io
  name: ai-platform-storage
  namespace: ai
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-csi
  mountOptions:
    - nolock
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: ai
    volumeAttributes:
      server: unas.internal
      share: /var/nfs/shared/ai_platform_data
    readOnly: false
