---
apiVersion: aigateway.envoyproxy.io/v1alpha1
kind: AIGatewayRoute
metadata:
  name: ai-gateway-routes
  namespace: ai
spec:
  schema:
    name: OpenAI
  targetRefs:
  - name: ai-gateway
    kind: Gateway
    group: gateway.networking.k8s.io
  rules:
  - matches:
    - headers:
      - type: Exact
        name: x-ai-eg-model
        value: llama3:latest
    backendRefs:
    - name: ollama-backend-service
  # - matches:
  #   - headers:
  #     - type: Exact
  #       name: x-ai-eg-model
  #       value: gpt-4o-mini
  #   backendRefs:
  #   - name: openai-backend-service
  # - matches:
  #   - headers:
  #     - type: Exact
  #       name: x-ai-eg-model
  #       value: us.meta.llama3-2-1b-instruct-v1:0
  #   backendRefs:
  #     - name: aws-bedrock-backend
