---
replicaCount: 3
# nodeSelector:
#   nvidia.feature.node.kubernetes.io/gpu: "true"
podSecurityContext:
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault
  fsGroup: 1000
securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: nvidia.com/gpu.present
              operator: In
              values:
                - "true"
persistentVolume:
  enabled: true
  storageClass: local-path
updateStrategy:
  type: Recreate
ollama:
  gpu:
    enabled: true
    type: 'nvidia'
    number: 1
ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: lets-encrypt-prod
  hosts:
    - host: &host ollama.local
      paths:
        - path: /
          pathType: Prefix
  # tls:
  #   - hosts:
  #       - *host
  #     secretName: ollama-api-tls-domain