---
ollama:
  enabled: false

podSecurityContext:
  fsGroupChangePolicy: Always
  fsGroup: 1001
containerSecurityContext:
  runAsUser: 1001
  runAsGroup: 1001
  runAsNonRoot: true
  privileged: false
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: false
  capabilities: { drop: ["ALL"] }
  seccompProfile: { type: RuntimeDefault }
persistence:
  enabled: true
  # existingClaim: open-webui
pipelines:
  enabled: false
ollamaUrls: ["http://ollama.ai.svc.cluster.local:11434"]
extraEnvVars:
  - name: WEBUI_SECRET_KEY
    value: "key"
# ingress:
#   enabled: true
#   class: "nginx"
#   annotations:
#     cert-manager.io/cluster-issuer: cloudflare-issuer
#   host: ollama.local
#   tls: true
  