---
apiVersion: v1
kind: Pod
metadata:
  name: ollama-test-connection
  namespace: ai
spec:
  securityContext:
    seccompProfile:
      type: RuntimeDefault
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: nvidia.com/gpu.present
                operator: In
                values:
                  - "true"
  containers:
    - name: wget
      securityContext:
        allowPrivilegeEscalation: false
        runAsNonRoot: false
        capabilities:
          drop:
            - ALL
        seccompProfile:
          type: RuntimeDefault
