---
apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: ksops
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - llm-providers/openai/secret.enc.yaml
  - llm-providers/bedrock/secret.enc.yaml
