apiVersion: v1
kind: Secret
metadata:
    name: openwebui-secrets
    namespace: ai
stringData:
    webui_secret: ENC[AES256_GCM,data:M33jmBSHPJBvfmK3LET4hzzDu8F/VIkHr+sI37A=,iv:zDmbfy0cQ7D1X0ZTr6y5yn5Jzr/JBNqUIKMukQW2ofU=,tag:1LjCU7SP8lLvjUDsnk3yYA==,type:str]
    github_token: ENC[AES256_GCM,data:EcfKQQiv0qoZh5euTXsEPVtyxbryZSYoBQzz8E0elUqfKKY8cHB0Cg==,iv:tG627DJcrLMKnEqvsb7mmUR3PNJ1hdbDtFJZ9DslDvo=,tag:9SmsbJbRvO4KGdRZSNxZBg==,type:str]
    n8n_api_key: ENC[AES256_GCM,data:rUxjeIpfJaLm3FAQ1gl9vywonJVHa4cKglHiLwbbbA2NkRY/MG9OWdV2ADVV6jiuG+j80nJAO52Paw/TNJiOGRMtYFLaqtgg8svt+CUeActTu2SotfqFE74PaOlgO09ollPbmeRiy3AUHKzwb4gMFsTZCWEblGBUwl+L7K24DJdesZl7jCZqbKeyiS3Z3e4ST7i1koClZbyO6WSH3CHvzhK2CA8ciyw2X4xx9ggvJffQW7hCiNxwDDbWWzGGVL9eCg/Itqgle7cmKbYagdZB,iv:xgZ0yJVEkXliTxAkcZgwHp4PmATXQnanLBsnVXJRYkM=,tag:MrLi/kFroHIAwl/AUK+b7Q==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:626956831217:key/f22ea8b8-ec28-4d80-988e-7372419dbc28
          created_at: "2025-02-17T21:31:51Z"
          enc: AQICAHgf2Bz/yC/N+d80dqtXyzpCypiaZx1Lgwl8YcJR1TYnOAG+YW/kkde8eEEqwirdCIwLAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMOOQkWvNS/Pz4Yv8qAgEQgDvWxD+ysovN027HT7mbVLhRrSIpZMaZxW+bcTUjjPGVnsk1l1cxiVQRGtUCxOOeAlXFg85062+NMlOQTQ==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-02-17T21:31:51Z"
    mac: ENC[AES256_GCM,data:/xfb18C2IS7Ug9WOdxeNQXziTqVLrKkrlhgfRr2UX0jX+26NWdP8K5wF0xSEI0DjKHJVOTiQn3iE1JAnmwKycxwvvSjJAK+tXDit907uZtswUz2QzRhAx6HgyE/wwDjJ8Hm83xvtw76s9+TguCHhwcO/bc7D+2kWpfmYQVhUm/0=,iv:WOdT0/Lhh91TPxKMJxrh5UQpiMPp7TVCuDfICL8J77A=,tag:xxkitx9sA97UpjUQcK6dJQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
