---
version: 3

tasks:
  deploy:
    cmds:
      - |-
        kustomize build ./ai/k8s --enable-helm --enable-exec | \
          kubectl apply -f -

  destroy:
    cmds:
      - |-
        kustomize build ./ai/k8s --enable-helm --enable-exec \
          | kubectl delete -f -
