services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
    volumes:
      - ./grafana:/etc/grafana/provisioning
      - grafana-data:/var/lib/grafana

  # loki:
  #   container_name: loki
  #   image: grafana/loki:3.4.2
  #   restart: unless-stopped
  #   command: "-config.file=/etc/loki/config.yaml"
  #   ports:
  #     - 3100:3100
  #   volumes:
  #     - ./config/config.yaml:/etc/loki/config.yaml:ro
  #     - data_loki:/loki:rw

  # influxdb2:
  #   image: influxdb:2
  #   ports:
  #     - 8086:8086
  #   environment:
  #     DOCKER_INFLUXDB_INIT_MODE: setup
  #     DOCKER_INFLUXDB_INIT_USERNAME_FILE: ${INFLUXDB_ADMIN_USERNAME}
  #     DOCKER_INFLUXDB_INIT_PASSWORD_FILE: ${INFLUXDB_ADMIN_PASSWORD}
  #     DOCKER_INFLUXDB_INIT_ADMIN_TOKEN_FILE: ${INFLUXDB_ADMIN_TOKEN}
  #     DOCKER_INFLUXDB_INIT_ORG: docs
  #     DOCKER_INFLUXDB_INIT_BUCKET: home
  #   volumes:
  #     - type: volume
  #       source: influxdb2-data
  #       target: /var/lib/influxdb2
  #     - type: volume
  #       source: influxdb2-config
  #       target: /etc/influxdb2

volumes:
  grafana-data:
  # influxdb2-data:
  # influxdb2-config:
  # data_loki:
  #   driver: local
