---
version: 3

vars:
  KUSTOMIZE_FLAGS: --enable-helm --enable-exec --enable-alpha-plugins

tasks:
  deploy:
    cmds:
      - |-
        kustomize build {{.KUSTOMIZE_FLAGS}} ./observability | kubectl apply -f -

  destroy:
    cmds:
      - |-
        kustomize build {{.KUSTOMIZE_FLAGS}} ./observability | kubectl delete -f -
