---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: automation
resources:
  - namespace.yaml
  - automation-platform-storage.yaml
  - postgres
  - n8n
  - scrapers
generators:
  - secrets-generator.yaml
