---
apiVersion: kagent.dev/v1alpha1
kind: MCPServer
metadata:
  name: github-mcp-server
  namespace: ai
  labels:
    app: github-mcp-server
spec:
  deployment:
    args:
    - 'stdio'
    cmd: "/server/github-mcp-server"
    image: ghcr.io/github/github-mcp-server
    port: 3000
    env:
      GITHUB_PERSONAL_ACCESS_TOKEN: "REPLACED_BY_KUSTOMIZE"
  transportType: stdio
