apiVersion: ENC[AES256_GCM,data:yqw=,iv:S5SkjBuO5aM7ckBmM6nWg5pA8wq9CV3NbY66uSVJFZo=,tag:t6m3h34xc/iFZGRZkau8GA==,type:str]
kind: ENC[AES256_GCM,data:984cDjF0,iv:XEEfbjHKWCgCbeQod5wK4LzmMXGSLp3T/5xYIkKUN6M=,tag:Rkyp23wkPvKY8UlU5dhF6w==,type:str]
metadata:
    name: ENC[AES256_GCM,data:fVNk/5bkXBjMmbk=,iv:5QyuwuofuGAw7vh/wg51EL7ed7/JuyB9g1+mLS6atlY=,tag:QKB8lhqMf4sNZFimaLHDjg==,type:str]
    namespace: ENC[AES256_GCM,data:qPc=,iv:Cx19MeJRo+cG7F2JAdYrjXhicbd3FKAr07g1Lctnd0s=,tag:eaCj+96YcBE0S1M513A8VQ==,type:str]
stringData:
    GITHUB_PERSONAL_ACCESS_TOKEN: ENC[AES256_GCM,data:pp/cUfngmEBGJHA4LHjBF8TphVO9WGCsYfzxjYJIuQnDuRvtgH7eNA==,iv:jIB1ufCTGbj7ixAy6DsEfWXAjV7y9FzO9FOodsElbik=,tag:QQWbWGvacE5j4hfNmCXKxw==,type:str]
    CONTEXT7_API_KEY: ENC[AES256_GCM,data:6sPLe5aihYGU3FOSVnvIEY5W9Bc8FvdS4cxjkXLCmuafCr8aHWIagsjKtQ==,iv:DntEFtkEcMZuAVQ+N5tDBURkflA9ZsGgn+gJM2bh5HM=,tag:gbYNXEM0GiInSQLQ5eCVRA==,type:str]
    QDRANT_API_KEY: ENC[AES256_GCM,data:5wCH/1vX/LnBc+6uHF3Ltdz/gULSAKEe2w==,iv:LD+2BACX6RlsXD+HPFCz51akm+xJJ0MQLTXExEU/Oqs=,tag:1+ApK77NoC7OcvChls0cgw==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:626956831217:key/f22ea8b8-ec28-4d80-988e-7372419dbc28
          created_at: "2026-10-08T21:18:44Z"
          enc: AQICAHgf2Bz/yC/N+d80dqtXyzpCypiaZx1Lgwl8YcJR1TYnOAG9x4paOZdTNUQR8NiguXITAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMdwQXNPqGAAf9hbZVAgEQgDt/bUfq3A+SwQZAEQksHkmNM74frpdxp508IlssH9Qm0yo2bDre9XhCrLemlYE36qx6Qkckk4hMuv/Dgw==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-10-08T21:18:44Z"
    mac: ENC[AES256_GCM,data:gMfRxZCKD+zf7A78kAMgDNWHP2DB0HhhzoodhP2nZK6URC56cca2I+n3wv31Gyz4Llfjd3wW8GRZypUvWi4pHxkfS3WCYKPSGE8/aodTzakeQwlaGC7HnCzaC/URXfWmYfdbbvGtQe8nUjMr8gkEUmXllopIlSwtjyh4cr0XATU=,iv:4rN9ajGfzou/xwfd8stHjukD3fBrONwdpcXvupvx5z4=,tag:hqk/L1ABUHW1+I47TQQcxA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|apiVersion|metadata|kind|type)$
    version: 3.8.1
