apiVersion: ENC[AES256_GCM,data:FQM=,iv:abXaOiN2OaCKI47uBJi9/j6n4B8ROzmKBzpRS45WW3o=,tag:u9PBml2CRMGarmsvAfxCiw==,type:str]
kind: ENC[AES256_GCM,data:7wIHhcJA,iv:gMkgl6q11/scmv/nTDaWU7Z3+eQWjQOXVOAqM8B6hzo=,tag:vViVH5viZVwhlnirQ5HYVQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:8x7GK2n2BUEbcEo=,iv:0PNCa6d495D9Rg2rt9CSS+Y8jdYLzKua8BKAQxrKLTE=,tag:mEoBjZVIcffjp/O7S5tUwA==,type:str]
    namespace: ENC[AES256_GCM,data:gGs=,iv:cH6TBhR/ixQdQF++3ynU6KTdfiC93WTDmfCm41yeTdg=,tag:xHHsfeG4KCPGutEA4khlSA==,type:str]
stringData:
    GITHUB_PERSONAL_ACCESS_TOKEN: ENC[AES256_GCM,data:10IT41S5zSC9ACdfCG9YYRwCqeRmdIhdKmIk9jF4GVSdaKPzeUUABw==,iv:jfeabTSlblLiupzBiyFa74ENgsuBY+blDVd2iTe8dAE=,tag:ninfTO1LhCLOBj/ph52Gtg==,type:str]
    CONTEXT7_API_KEY: ENC[AES256_GCM,data:H3exIouRiAqIUiJD+sTFkuBcyp6l/m/umjWxgMWy23np1+cPrVeKLOnEYQ==,iv:PbJo/hZ661tVdv3ESTaSWNgK2bplw1AtFEhCrMTBCnM=,tag:qb6nOuzycCPzckqrnxotxA==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:626956831217:key/f22ea8b8-ec28-4d80-988e-7372419dbc28
          created_at: "2026-06-17T19:40:16Z"
          enc: AQICAHgf2Bz/yC/N+d80dqtXyzpCypiaZx1Lgwl8YcJR1TYnOAEkIp3e0dpPVGbns6KN9iRlAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM2DL+AnM94Fi5l8Z7AgEQgDv1Dl0MPXvOeyWK5FBe1JAySzLgX0aq3sGQV+caDv8XVqJL6x60FOBQsU6xHudPH1aRiv4yLisaAwQVAQ==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-06-17T19:40:16Z"
    mac: ENC[AES256_GCM,data:KUrVC79AvI/I96Yr2Y9ffQP6ZIw2RNedUtRQ/a27eBeb1PgX0tYoFY5o/6fVNoKWMV10xy8ljEl0W2tO80pq6LOVRsbRta9bUEU6YzkteyHH8OoLsm48O0m+CX1fa4FU2r/O/AmzOjhxDZr8BP3Iu1Rnt8metxEjy/51YvICfeM=,iv:fehL/vEJ6ggASJ4jXXY5hX74/IU5SQPEEV6HCz1uIZQ=,tag:TuJmvXsNwnG5c5naTELrLg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|apiVersion|metadata|kind|type)$
    version: 3.8.1
