services:
  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    env_file: .env
    ports:
      - 3000:8080
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped