apiVersion: ENC[AES256_GCM,data:vKI=,iv:KY/EXDmCxAazsXoKcbaWziW+Dx9FGWP8mdkfgvqW80M=,tag:TJJHMiPFy5zBGaKTTt6bGw==,type:str]
kind: ENC[AES256_GCM,data:8fcLsD2x,iv:R+PpbuFEfJ81e+rRTh6R8p1f2c0i0MpKb82LMMoY714=,tag:hv8nvHlJ5ZnPe3uhhwlFuw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:vBury/3yoU3pgtQ8juM=,iv:4qkfhiEZp5ZFZPUagXZcc52A2TMX0l5mjOnuzqWlBiA=,tag:SREKa6/6XQ+Fz7tHVVufaQ==,type:str]
    namespace: ENC[AES256_GCM,data:8DFzFb7zVhw8Q6cIEw==,iv:32Ln9lU48gaBxGqs9/GCZbIKcSZc2WK84IOGSYs7jas=,tag:zgWrIKyhZIxSTc+vHTTYsw==,type:str]
type: ENC[AES256_GCM,data:4kpFWmhQ,iv:z77KlT/YwDvPuN8LkBwrK1lRaddG3Q14lqcO5yXqAC0=,tag:pAUjjhNEW386fipxBEv/0w==,type:str]
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:2msy/Q==,iv:i3IDZFb5N2tYtpij4pmjDAZZZrZK8PpY0QcIAFyif90=,tag:UIjDSwzcRU8KAsYzYVI5cg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:X1hL/UW6VREwqzMCKqWe57tmzGy4M1GqwVyadMPF5pcz7G/U//5imCFPh5g2TbtCbK49eEFoV4EmeD7b35gyuQ==,iv:OXdIjYqV5EbxwUOBVhrGqJ8L9KdjC7pVwv3f4EnVDPY=,tag:tJrIYch0a6WdY+fPJcCERQ==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:626956831217:key/f22ea8b8-ec28-4d80-988e-7372419dbc28
          created_at: "2026-07-20T21:16:41Z"
          enc: AQICAHgf2Bz/yC/N+d80dqtXyzpCypiaZx1Lgwl8YcJR1TYnOAE4YComs2Tenfle8tthUXf+AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMRsyOU4GR06TpZVt1AgEQgDt25BmhTBzRAsFJA439tFslMetaQTte70Jd9rr9McITyMV/XlpJ5AFpILvkFjN2fJlYNnlriYVFsBmW5w==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-07-20T21:16:41Z"
    mac: ENC[AES256_GCM,data:RQY/UjL9TU8XkPkHY8YjhBv5GdrBgFGFhcB53xRhaO8ZzVN6Mp/SkrF7HX2rIwoJkXshwdiGpmUSDCaHJAovtVEsijDmTcx9WoDMHT79x+aipp+UTzKMuc7rpvwAaADI/k6luZCwIbQpI7oyGxxpiH1CCXmK8OYXTjFRjv73gAM=,iv:QgQsIPIj46NTerkylrijyLegoUk6NbZj+aeimEumbdA=,tag:bshdHCSvP8tH+U2bqGUB/g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|apiVersion|metadata|kind|type)$
    version: 3.8.1
