---
machine:
  features:
    kubernetesTalosAPIAccess:
      enabled: true
      allowedRoles:
        - os:reader
        - os:admin
      allowedKubernetesNamespaces:
        - system-upgrade
        - default
