apiVersion: v1
kind: Secret
metadata:
    name: aws-credentials
stringData:
    aws_access_key_id: ENC[AES256_GCM,data:ik0wEf/fnvtDTCAtmHKI/tupmEw=,iv:hw4mk7OQgrnxapOFY6Ih8pvFHYT763Ua75ajFhgZ3H8=,tag:Fgg0St3+dDfwqoq2DUWT/Q==,type:str]
    aws_secret_access_key: ENC[AES256_GCM,data:zhpIKEXoMjfCFWZVVnba/f4jzv9bVEasfuhTSPdv7Px+iwJzfMVhqw==,iv:1GZIIvkiiq6UiitkZEXAYIiwsn3brrUCSy2ECD9yEr8=,tag:gkpvzdsO8VWsmupvk5wXLw==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:626956831217:key/f22ea8b8-ec28-4d80-988e-7372419dbc28
          created_at: "2025-01-23T18:52:03Z"
          enc: AQICAHgf2Bz/yC/N+d80dqtXyzpCypiaZx1Lgwl8YcJR1TYnOAHVlibA55nWRrRM0ll4OVKkAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMYA3ujH6Fdlz8RP2YAgEQgDswVWaTxOYCxy70RW2r2v39MEDtJJgH2QWb/0f2W1ICCGPHXcRQ32TjYZeHUi6UpuruVCR6vaWeNmlJEQ==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-01-23T18:52:03Z"
    mac: ENC[AES256_GCM,data:GPEarUlXORBjhoifC4U1OJP1eX0pJD+ERGWlLUdu6hOPFrAXc5VMmZLNC26uqEJBUrJbX1s5vYVVlV/4lQr+I4iKMtFvQpFYIUropXX7aaIeDZlQUz/6R4J+87OnkNI1KGNHFY/Chp3FEQ3GasK8/3gDmJi2tOcM0wDon7s0kwg=,iv:5zWMsr5KJQ1NuKyoMJDRaQt93B3uojfzCH+BvkFASeA=,tag:4Tn1jtQGcw2/vinbryei+g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
