apiVersion: v1
kind: Secret
metadata:
    name: aws-credentials
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
stringData:
    aws_access_key_id: ENC[AES256_GCM,data:eWLMTYdCCtQcC8Ti/vwTyWjT0GE=,iv:Smk7YVcBEmrspR/OnnC5GEq8CY1MtfFqP9k5iQDZnrY=,tag:NlbZhq9Cd8+ec/gzaG+9CA==,type:str]
    aws_secret_access_key: ENC[AES256_GCM,data:OtDGRdjYJWwkjIFR5r+VWtSUJZXAS9x7assJwpte2DTA1ZlCzaldXg==,iv:upoIGzAyG8i42e+lFMEEF7eORfy+h/2xDM66eyNfnPM=,tag:aVLdXRLTlGALAt0eeUXnrw==,type:str]
    aws_homelab_remote_state_backup: ENC[AES256_GCM,data:j1yrEo4B9rEriYjBNtw0gTz523n6LXhU83Uy3P9jtMQ=,iv:cBs5G0E7wcLBp8+PcO/b55sK6b8DzEsrSa9fPqKkfO8=,tag:IwlDXw+EfnS1pnZg11qdaA==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:626956831217:key/f22ea8b8-ec28-4d80-988e-7372419dbc28
          created_at: "2025-02-15T20:40:27Z"
          enc: AQICAHgf2Bz/yC/N+d80dqtXyzpCypiaZx1Lgwl8YcJR1TYnOAGtEN6pk66JmzObvTWTBM9CAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMFFYhx+s621lVLRnWAgEQgDsFJMWaIdi08v2Z/n2DOQ3lkEZZgfD/g7GdTBm5cz9f0bwa46ARjcJzIsYj+8JuYxaFZaNTH0KvRWa55g==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-02-15T20:40:27Z"
    mac: ENC[AES256_GCM,data:5N1fX3BIsiRF/7e7oXD/bs1JL/msXQgY918RI7r5yBEwF8YT0qGoHOzRqvjR6R3wA9rAFaLvDZMDliEX4aMJ5X8XNnbTF6LAdzvYxLaN8hBMK5rLlipwGy7uSNigRuIHKAIhR6Tehx/WQ+UZAk1MH/m+Gu42Jb+7v5QU0fL2jZI=,iv:LDJ8aKvu9ThpDlSQU32TvjlP8BkGfgidf52CbiB3ZQw=,tag:ljfC1TLcD0IPjA8mb/dIIg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
