customization:
  extraKernelArgs:
    - net.ifnames=0
  systemExtensions:
    officialExtensions:
      - siderolabs/intel-ucode
      - siderolabs/qemu-guest-agent
      - siderolabs/nvidia-container-toolkit-production
      - siderolabs/nonfree-kmod-nvidia-production
