customization:
  systemExtensions:
    officialExtensions:
      - siderolabs/qemu-guest-agent
      - siderolabs/nvidia-container-toolkit-production
      - siderolabs/nonfree-kmod-nvidia-production
