customization:
  extraKernelArgs:
    - intel_iommu=on
    - iommu=pt
    - net.ifnames=1
  systemExtensions:
    officialExtensions:
      - siderolabs/intel-ucode
      - siderolabs/qemu-guest-agent
      - siderolabs/nvidia-container-toolkit-production
      - siderolabs/nonfree-kmod-nvidia-production
