---
helmfiles:
  - path: ../../helmfile.d/01-bootstrap.gotmpl.yaml
    values:
      - cluster: application
      - identityOverlay: ../clusters/application/identity-values.yaml.gotmpl
      - meshOverlay: ../clusters/application/clustermesh-values.yaml.gotmpl
