---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nvidia-device-plugin
  namespace: kube-system
spec:
  template:
    spec:
      initContainers:
        - name: nvidia-device-plugin-init
          image: nvcr.io/nvidia/k8s-device-plugin:v0.17.0
          resources:
            limits:
              cpu: 150m
              memory: 512Mi
            requests:
              cpu: 150m
              memory: 256Mi
      containers:
        - name: nvidia-device-plugin-sidecar
          image: nvcr.io/nvidia/k8s-device-plugin:v0.17.0
          resources:
            limits:
              cpu: 150m
              memory: 512Mi
            requests:
              cpu: 150m
              memory: 256Mi