---
#  config:
#   map:
#     default: |-
#       version: v1
#       flags:
#         migStrategy: none
runtimeClassName: nvidia
securityContext:
  privileged: true
nodeSelector:
  feature.node.kubernetes.io/pci-10de.present: "true"
gfd:
  enabled: false