---
apiVersion: agentgateway.dev/v1alpha1
kind: AgentgatewayBackend
metadata:
  name: mcp-backend
  namespace: ai
spec:
  mcp:
    targets:
      - name: kagent-tools
        static:
          host: kagent-tools.ai.svc.cluster.local
          port: 8084
          path: /mcp
      - name: kagent-querydoc
        static:
          host: kagent-querydoc.ai.svc.cluster.local
          port: 8080
          path: /mcp
      - name: kagent-grafana
        static:
          host: kagent-grafana-mcp.ai.svc.cluster.local
          port: 8000
          path: /mcp
