---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: prometheus
    repo: https://prometheus-community.github.io/helm-charts
    version: 27.8.0
    namespace: observability
    releaseName: prometheus-community
    # valuesInline:
