---
version: 3

tasks:
  list-ai-pods:
    desc: List all AI pods
    cmds:
      - kubectl get pods -A -o wide | grep -E 'nvidia|cuda'

  launch-dns-debugger:
    cmds:
      - kubectl run -it --rm --restart=Never --image=infoblox/dnstools:latest dnstools
