---
apiVersion: v1
kind: Service
metadata:
  name: chatui
  namespace: ai
spec:
  type: ClusterIP
  selector:
    name: chatui
  ports:
  - port: 3000
    name: http
    targetPort: http
    protocol: TCP
