apiVersion: v1
kind: ConfigMap
metadata:
  name: rss-feeds
data:
  feeds.yaml: |
    feeds:
      - name: "Hacker News"
        url: "https://rsshub.local/hackernews/frontpage"
      - name: "GitHub Trending Python"
        url: "https://rsshub.local/github/trending/python/daily"
      - name: "Reddit AI Subreddit"
        url: "https://rsshub.local/reddit/subreddit/artificial"
