---
hooks:
  - events: ["prepare"]
    showlogs: true
    command: "bash"
    args:
      - -c
      - kustomize build ../apps/storage/local | kubectl apply -f -
      - kustomize build ../apps/namespaces | kubectl apply -f -