---
bases:
  - ../defaults.yaml

repositories:
  - name: nfd
    url: https://kubernetes-sigs.github.io/node-feature-discovery/charts
  - name: nvidia
    url: https://nvidia.github.io/k8s-device-plugin

releases:
  - name: node-feature-discovery
    chart: nfd/node-feature-discovery
    version: 0.17.1
    namespace: kube-system
  
  - name: nvidia-device-plugin
    namespace: kube-system
    chart: nvidia/nvidia-device-plugin
    version: 0.16.2
    needs:
      - kube-system/node-feature-discovery
    values:
      - runtimeClassName: nvidia
      - devicePlugin:
          enabled: true
        gfd:
          enabled: true
        nfd:
          enabled: false
