---
bases:
  - ../defaults.yaml

repositories:
  - name: nvidia
    url: https://nvidia.github.io/k8s-device-plugin
  - name: gpu-helm-charts
    url: https://nvidia.github.io/dcgm-exporter/helm-charts
  - name: kwasm
    url: http://kwasm.sh/kwasm-operator/

releases:
  - name: nvidia-device-plugin
    namespace: kube-system
    chart: nvidia/nvidia-device-plugin
    version: 0.17.1
    values:
      - runtimeClassName: nvidia
      - devicePlugin:
          enabled: true
        gfd:
          enabled: true
        nfd:
          enabled: true
      # - config:
      #     map:
      #       default: |-
      #         version: v1
      #         sharing:
      #           timeSlicing:
      #             renameByDefault: false
      #             resources:
      #               - name: nvidia.com/gpu
      #                 replicas: 4
    hooks:
      - events: ["presync"]
        showlogs: true
        command: "bash"
        args:
          - -c
          - |
            kustomize build ../apps/hardware/nvidia | kubectl apply -f -

  - name: dcgm-exporter
    chart: gpu-helm-charts/dcgm-exporter
    namespace: kube-system
    needs:
      - kube-system/nvidia-device-plugin
    values:
      - nodeSelector:
          nvidia.com/gpu.present: 'true'
        runtimeClassName: nvidia
        hostNetwork: true
        resources:
          limits:
            nvidia.com/gpu: 1
        serviceMonitor:
          interval: 15s
          honorLabels: true
        service:
          enable: true
          type: LoadBalancer
          annotations:
            external-dns.alpha.kubernetes.io/hostname: dcgm.homelab.internal
        # extraEnv:
        #   - name: NVIDIA_VISIBLE_DEVICES
        #     value: all
        #   - name: NVIDIA_MIG_CONFIG_DEVICES
        #     value: all
        #   - name: NVIDIA_MIG_MONITOR_DEVICES
        #     value: all
        #   - name: NVIDIA_DRIVER_CAPABILITIES
        #     value: all

  - name: kwasm-operator
    chart: kwasm/kwasm-operator
    version: 0.2.3
    namespace: kube-system
    values:
      - kwasmOperator:
          installerImage: ghcr.io/spinframework/containerd-shim-spin/node-installer:v0.19.0

  - name: spin-operator
    chart: oci://ghcr.io/spinframework/charts/spin-operator
    version: 0.5.0
    namespace: kube-system
    needs:
      - kube-system/kwasm-operator
    hooks:
      - events: ["presync"]
        showlogs: true
        command: "kubectl"
        args:
          - "apply"
          - -f
          - https://github.com/spinframework/spin-operator/releases/download/v0.5.0/spin-operator.crds.yaml
          - -f
          - https://github.com/spinframework/spin-operator/releases/download/v0.5.0/spin-operator.runtime-class.yaml
      - events: ["postsync"]
        showlogs: true
        command: "bash"
        args:
          - -c
          - |
            kustomize build ../apps/hardware/wasm | kubectl apply -f -
