---
bases:
  - ../defaults.yaml

repositories:
  - name: nvidia
    url: https://helm.ngc.nvidia.com/nvidia
  - name: kwasm
    url: http://kwasm.sh/kwasm-operator/
  - name: metrics-server
    url: https://kubernetes-sigs.github.io/metrics-server/

releases:
  - name: gpu-operator
    namespace: kube-system
    chart: nvidia/gpu-operator
    version: 25.3.0
    createNamespace: true
    values:
      - runtimeClassName: nvidia
      - operator:
          defaultRuntime: nvidia
        toolkit:
          env:
            - name: CONTAINERD_CONFIG
              value: /etc/containerd/config.toml
        driver:
          enabled: true
        devicePlugin:
          enabled: true
          runtimeClassName: nvidia
        gfd:
          enabled: true
        migManager:
          enabled: false
        nfd:
          enabled: true
        validator:
          enabled: false
        dcgmExporter:
          runtimeClassName: nvidia
          hostNetwork: true
          nodeSelector:
            nvidia.com/gpu.present: 'true'
          serviceMonitor:
            interval: 15s
            honorLabels: true
    hooks:
      - events: ["presync"]
        showlogs: true
        command: "bash"
        args:
          - -c
          - |
            kustomize build ../apps/hardware/nvidia | kubectl apply -f -

  - name: kwasm-operator
    chart: kwasm/kwasm-operator
    version: 0.2.3
    namespace: kube-system
    values:
      - kwasmOperator:
          installerImage: ghcr.io/spinframework/containerd-shim-spin/node-installer:v0.19.0

  - name: spin-operator
    chart: oci://ghcr.io/spinframework/charts/spin-operator
    version: 0.5.0
    namespace: kube-system
    needs:
      - kube-system/kwasm-operator
    hooks:
      - events: ["presync"]
        showlogs: true
        command: "kubectl"
        args:
          - "apply"
          - -f
          - https://github.com/spinframework/spin-operator/releases/download/v0.5.0/spin-operator.crds.yaml
          - -f
          - https://github.com/spinframework/spin-operator/releases/download/v0.5.0/spin-operator.runtime-class.yaml
      - events: ["postsync"]
        showlogs: true
        command: "bash"
        args:
          - -c
          - |
            kustomize build ../apps/hardware/wasm | kubectl apply -f -

  - name: metrics-server
    chart: metrics-server/metrics-server
    namespace: kube-system
    version: 3.8.3
    values:
      - apiService:
          create: true
        metrics:
          enabled: true
        hostNetwork:
          enabled: true
        args:
          - --cert-dir=/tmp
          - --kubelet-use-node-status-port
          - --kubelet-insecure-tls
          - --kubelet-preferred-address-types=InternalDNS,InternalIP,ExternalIP,Hostname
          - --metric-resolution=60s
