---
bases:
  - ../defaults.yaml

releases:
  - name: kgateway-crds
    chart: oci://cr.kgateway.dev/kgateway-dev/charts/kgateway-crds
    version: v2.0.1
    installed: true

  - name: kgateway
    chart: oci://cr.kgateway.dev/kgateway-dev/charts/kgateway
    version: v2.0.1
    installed: true
    needs:
      - kgateway-crds
    values:
      - gateway:
          aiExtension:
            enabled: true
          inferenceExtension:
            enabled: true

  - name: homelab-gateway
    chart: ../charts/homelab-gateway
    needs:
      - kgateway
