---
apiVersion: gateway.networking.k8s.io/v1alpha3
kind: BackendTLSPolicy
metadata:
  name: openai-backend-tls
  namespace: ai
spec:
  targetRefs:
    - group: 'gateway.envoyproxy.io'
      kind: Backend
      name: openai-backend
  validation:
    wellKnownCACertificates: "System"
    hostname: api.openai.com
