---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: Backend
metadata:
  name: aws-bedrock-backend
  namespace: ai
spec:
  endpoints:
  - fqdn:
      hostname: bedrock-runtime.us-east-1.amazonaws.com
      port: 443
