apiVersion: ENC[AES256_GCM,data:FqE=,iv:0X4xfGhOJH9XdhUbO929prLXw9H4XbrQcnnhhXwzhh8=,tag:LHTimERhnhJFAy1BzSVhvw==,type:str]
kind: ENC[AES256_GCM,data:czjt7mGB,iv:AZnn6tvMautMqFPCeV9MBhmQhz+OALLbCdUVivZI6sM=,tag:CF2/LtB9P5lKnr4mkzPVkw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:YgVnW8dH0CTXQHkz0S2i558BQsQ=,iv:tSJOYrSQmOKT8g2SDgBDGDV/DNzuPUMOPpxZSwqt7DU=,tag:65Fi5PVlP6n4N2mNQxL0rw==,type:str]
    namespace: ENC[AES256_GCM,data:Oek=,iv:bZaezPpqvtkPs3d47Xn3Pz/MV9V5N/2jwvGTQfDa6wg=,tag:7EyQxcg2aHM2Q06StVAzXA==,type:str]
type: ENC[AES256_GCM,data:SUEmgCLs,iv:ujnAChdAFm76xNYyssRmcxX4fuGiAKsj1xF6zSoCR/U=,tag:tq2QKcRu2w/0/r4ackJquw==,type:str]
stringData:
    credentials: ENC[AES256_GCM,data:Uf5Htpx5WXur+rzRxnRdyTBHBuUJR4gVZTWL1m3lVdyP6l6ps3/A8hzhvrPMn9AsmfHb6TPN7znGhq6wgVHSXO657spbs2BJwUyKh+LwIfCM79cVrenxMUthlS9MUgbdebXReWP9+vUxkLvDMaGGLyjJBU4=,iv:gpLB+FWDFGIle1i2NVty0fZ/U3xrrPNuoUg4m4YIGiI=,tag:IfeMlQgWt3OWd7jjktLOlA==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:626956831217:key/f22ea8b8-ec28-4d80-988e-7372419dbc28
          created_at: "2025-04-02T18:29:17Z"
          enc: AQICAHgf2Bz/yC/N+d80dqtXyzpCypiaZx1Lgwl8YcJR1TYnOAHPBhU9veMHfCmaHiX+z8DuAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMh/spy221T/FHs1IVAgEQgDvnPx7qYVqpjRVtqhBH4CFMMmSD8TBZPv2QSP3p4dJTrFGj/YZE/KDx3kBWX5TtwN4K1ykBbZ0DRdyCXQ==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-04-02T18:29:18Z"
    mac: ENC[AES256_GCM,data:IljVVN+x+VXMCB/NnET0g1aYmL7NcI6e45TyEg7b/WSRHynXqLgftIZwcJArTq/8a/gF6gCqQwDObgqWmksDW8xZi56HoLi5R9Yb5cqBnsyV0PGo0512zd+/J9pp80kq5B47VyUjYH6WJsxDuUczVK6p+CHodw4+frqd/d4jqr4=,iv:j5ZXaGOqDY598X/WW+yHFv+ug+MUFoqaF3a/OmFqMgM=,tag:sonJhni/mmo4ighMW58QgA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|apiVersion|metadata|kind|type)$
    version: 3.8.1
