---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: automation
resources:
  - cronjob-charleston-licenses.yaml
  - cronjob-charleston-sales.yaml
images:
  - name: ghcr.io/nextgensolutions-llc/scrapers
    newTag: e422b94
