---
name: Deploy Docs

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-docs:
    name: Build Docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: yarn
      - name: Install dependencies
        run: yarn --cwd docs install --frozen-lockfile
      - name: Build website
        run: yarn --cwd docs build
      - name: Upload Build Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs

  deploy-docs:
    name: Deploy Docs
    needs: build-docs
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

