name: Pull Request Workflow

on:
  - pull_request_target

jobs:
  create_pr_labels:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v6
