---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: qdrant-pvc
  namespace: ai
spec:
  storageClassName: nfs-csi
  volumeName: ai-platform-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Gi
