apiVersion: ENC[AES256_GCM,data:YJE=,iv:0v4iu7nMG7w1YE1+3R6ZLSQz4ouuXVTOF2CfsBDpdoE=,tag:AyUJsm4Nm6ddEu7PW5QfmA==,type:str]
kind: ENC[AES256_GCM,data:UTubc+UU,iv:LBFlweYgpXQwzg+NT+7m9RRyAsVoJMNGfaRHHntZ7eA=,tag:vsGD6MpiOW+vRG4xMsis9Q==,type:str]
metadata:
    name: ENC[AES256_GCM,data:m32S0QYAymBZAnmuddQ=,iv:SKwfgnB24HUBQLxGcJIvy4v7gWt+ToYlyPcIfGo11Go=,tag:tOJo34pv+DXUctQ5yBuO3g==,type:str]
    namespace: ENC[AES256_GCM,data:mYQ=,iv:0tccNbvG/JrY/TVTY89h8qknn8ujeQrDMI8CANM0SfI=,tag:gObepO5ecghXDA0CZVvITQ==,type:str]
stringData:
    qdrant_api_key: ENC[AES256_GCM,data:98g3CahqzUp69TYLhoqnBaj0N/RX6FU4Gw==,iv:JS7xzRNgJ3L0wPx8baxTDvnoHvr4OOhsP1z6B4b5Z/8=,tag:OwDrCCDjDa/dZOpm6oPZ1Q==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:626956831217:key/f22ea8b8-ec28-4d80-988e-7372419dbc28
          created_at: "2025-07-04T11:05:17Z"
          enc: AQICAHgf2Bz/yC/N+d80dqtXyzpCypiaZx1Lgwl8YcJR1TYnOAFjb2ouhYQ31dDepS/sJe2gAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMlKaG+wSjmmS689nrAgEQgDsR2ctnVfztchaV4LdbEMpiUKnABe5WG8ucviEHGMWAoqcgffUH3dbhOSAnpczcYJ+phDHmlJcFv49D9w==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-07-04T11:05:17Z"
    mac: ENC[AES256_GCM,data:Y1XL6mSwZxtzPG8OmUh0Y6zZeB20qAzZRot8+uMYFFE8tP+yyuZ1H1xaRW6ntOsvQy22O/OYzkjhw3qWoPi8PnRjzlZVd6/n09CGF/LTdqX20E7bsDVYxiwdUcLPKG+rl27li6F9VJwoGNmtcrvJU0AleGHvAchwRi++rPv6RRI=,iv:iTCXZ2DpjXdMLhn1TQ0MI0lMvD5Ea2djmeX52yFA8jw=,tag:C6f3MBR9KL7uAmfpH7nqhQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|apiVersion|metadata|kind|type)$
    version: 3.8.1
