apiVersion: ENC[AES256_GCM,data:gJ8=,iv:WDhNZil70gVbmvT/88Oqnu0siUSqAVI7QyLiYxrz37k=,tag:0YXsGGp763gnoluAQuj3qQ==,type:str]
kind: ENC[AES256_GCM,data:MWEIfnMZ,iv:qdvZyl+Wu/Baw2do8ZJMPvfaiqfyPouIVmn8sW9wr4w=,tag:5kNDwdUq0xNzMBoVQKC2Mg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:ZdhCCygVk9xOf52tUrauU7PC,iv:LLoPgpmpIfwF0iFSPYf/BRVYJaDIUF0jmLR74p4SK/A=,tag:w4Pn7a5X6TYxIg72HUvGxg==,type:str]
type: ENC[AES256_GCM,data:hKyY3kl2,iv:LM/ok1xylYs9ZNQdTbXeQzJiSNOAcM3BImHQHstEYmc=,tag:dwpCI4d7xu1wP2z+dyWz4g==,type:str]
stringData:
    dummy_password: ENC[AES256_GCM,data:3/othnU6Lp41wq0oD85fGhK0kN7VwWWdvNk0QROnUFNuFyVu+q5qVedR8oiHpeBU,iv:KYHAKH6nJ2bhJQ5ahC389OzQjY0Xse/6wvwQyfvPQCU=,tag:HO7O4NCH80eQfB6s0GgrLA==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:626956831217:key/f22ea8b8-ec28-4d80-988e-7372419dbc28
          created_at: "2026-07-02T19:42:23Z"
          enc: AQICAHgf2Bz/yC/N+d80dqtXyzpCypiaZx1Lgwl8YcJR1TYnOAG9q8Q1xFsxUeKfowoYNAtVAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMzC4wZgVwd8dZMEBcAgEQgDuCRYM96AYEYCIWY0vZcJHUbXS8CXer6SMR391v0mITn9o6q2W3tTgzwLLQ4pr7WlrmkH9LfBPMb8/g9Q==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-07-02T19:42:23Z"
    mac: ENC[AES256_GCM,data:V5SiedNeuimcDxw7h/MkmK5tWfrLHhUBsHA52XTK7lAjUgxxKIyvYI20vi5E2OvHgP0/XayGAgVoRomYwzz9SoJLEOAPfNb0NLRZjmJYLyjpHajgk0Bds6d2xquqJXcSMqqkUB8rwZDOqc6flrTPQqVri9gVx5UkJh0VeyMrf0I=,iv:L4vzJ6lkjimQKZeVquj/0BlYLNUvwNzGmFU9q5iWo10=,tag:PiIujsq6S045YfAzhbQh2Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|apiVersion|metadata|kind|type)$
    version: 3.8.1
