[tool.poetry]
name = "assistant"
version = "0.1.0"
description = ""
authors = ["teaglebuilt <dillan.teagle.va@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
huggingface-hub = "^0.26.5"
transformers = "^4.47.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
